'use client'
import { useRef, useState, useEffect, type FormEvent } from 'react'
import Link from 'next/link'
interface Quote {fee:number;distance:number;zip:string;isEstimate:boolean;distanceBasis:string}
function deliveryZipFromInput(value:string):string|null{const match=value.trim().match(/(?:^|[,\s])(\d{5})(?:-\d{4})?(?:\s*,?\s*(?:USA|United States))?\s*$/i);return match?.[1]||null}
export default function DeliveryFeeChecker(){
 const [address,setAddress]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[quote,setQuote]=useState<Quote|null>(null)
 const active=useRef<AbortController|null>(null);useEffect(()=>()=>active.current?.abort(),[])
 const change=(value:string)=>{active.current?.abort();active.current=null;setAddress(value);setQuote(null);setError('');setLoading(false)}
 async function submit(e:FormEvent){e.preventDefault();active.current?.abort();setQuote(null);setError('');const zip=deliveryZipFromInput(address);if(!zip){setError('Enter a five-digit ZIP code, or include it at the end of your event address.');return}const controller=new AbortController();active.current=controller;setLoading(true);const timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch('/api/delivery-fee?zip='+encodeURIComponent(zip),{signal:controller.signal,cache:'no-store'});const data=await response.json();if(!response.ok||typeof data.fee!=='number'||!Number.isFinite(data.fee)||data.fee<=0||data.zip!==zip)throw new Error(data.error||'A delivery fee could not be calculated. Please retry.');if(active.current===controller)setQuote(data)}catch(err){if(active.current===controller)setError(controller.signal.aborted?'The delivery lookup timed out. Please try again.':err instanceof Error?err.message:'Delivery pricing is temporarily unavailable. Please retry.')}finally{clearTimeout(timer);if(active.current===controller){active.current=null;setLoading(false)}}}
 return <section id="delivery-estimate" className="bg-[#0B1F3A] px-4 py-10 text-white md:py-14"><div className="mx-auto max-w-5xl"><p className="text-xs font-extrabold uppercase tracking-widest text-[#F4C542]">NYC / Lower Westchester delivery checker</p><h1 className="mt-3 font-serif text-3xl font-bold md:text-4xl">See your delivery fee before you book</h1><p className="mt-3 max-w-3xl leading-7 text-white/80">Enter your event ZIP code, or an event address ending in the ZIP. NYC delivery uses fixed ZIP-zone pricing for the currently supported Riverdale, Northwest Bronx and Lower Westchester service area.</p><form onSubmit={submit} className="mt-6"><label htmlFor="delivery-address" className="mb-2 block text-sm font-bold">Event address with ZIP code, or ZIP code</label><div className="flex flex-col gap-3 sm:flex-row"><input id="delivery-address" value={address} onChange={e=>change(e.target.value)} placeholder="Riverdale, NY 10471" autoComplete="street-address" className="min-h-12 min-w-0 flex-1 rounded-xl border border-white/30 bg-white px-4 py-3 text-[#0B1F3A]"/><button type="submit" disabled={loading} className="min-h-12 rounded-xl bg-[#F4C542] px-6 py-3 font-extrabold text-[#0B1F3A] disabled:opacity-60">{loading?'Checking…':'Check Delivery Fee'}</button></div></form><div aria-live="polite" className="mt-4">{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{quote&&<div className="rounded-xl border border-white/20 bg-white/10 p-5"><p className="text-sm">Delivery fee for ZIP {quote.zip}</p><p className="mt-1 text-3xl font-extrabold">{'$'}{quote.fee.toFixed(2)}</p><p className="mt-2 text-sm leading-6 text-white/80">Delivery only—customer warehouse pickup is not available. Rental charges, tax and optional services are separate. Confirm your event details and total at checkout.</p><Link href="/order-by-date" className="mt-3 inline-block font-bold text-[#F4C542] underline">Check my event date →</Link></div>}</div><p className="mt-4 text-xs leading-5 text-white/65">This is a ZIP-zone fee, not a warehouse-mile calculation. Contact the NYC team if your ZIP is not currently listed.</p></div></section>
}
