'use client'

import Link from 'next/link'
import Image from 'next/image'; import { useRouter } from 'next/navigation'; import { trackEvent } from '@/lib/gtag'
import type { ReactNode } from 'react'
import ReviewCarousel from './ReviewCarousel'
import DesignYourEventCTA from './DesignYourEventCTA'
import { formatCurrency } from '@/lib/utils'
import { ImageOff } from 'lucide-react'
import YouTubeFacade from './YouTubeFacade'

interface MobileCategory { slug:string; name:string; href:string; image?:string }
interface MobilePopularItem { id:string; name:string; slug:string|null; cost:number; picture:string|null; status?:string|null; category?:{name:string|null}|null }
interface MobileHomeProps { categories:MobileCategory[]; popularItems:MobilePopularItem[]; bounceItems:MobilePopularItem[]; weddingImage?:string|null; packages:{id:string;name:string;price:number;guests:number;image?:string|null;popular?:boolean;signature?:boolean}[]; seoSection:ReactNode; hero?:any; heroEditMode?:any; content?:Record<string,string>|null; contentEditMode?:any; categoryEditMode?:any }
const HERO_IMAGE='/images/mobile-hero-event-scene-v4.png'
function EditableText({id,value,as:Tag,className,contentEditMode}:{id:string;value:string;as:any;className?:string;contentEditMode?:any}){const C:any=Tag;if(!contentEditMode)return <C className={className}>{value}</C>;const selected=contentEditMode.selectedKey===id;return <C className={(className||'')+' '+(selected?'outline outline-2 outline-blue-500 outline-offset-2 cursor-pointer':'cursor-pointer hover:outline hover:outline-2 hover:outline-blue-300 hover:outline-offset-2')} onClick={(e:any)=>{e.preventDefault();e.stopPropagation();contentEditMode.onSelect(id)}}>{value}</C>}
export default function MobileHome({categories,popularItems,bounceItems,weddingImage,seoSection,packages,hero,content,contentEditMode}:MobileHomeProps){const router=useRouter();const heroImageSrc=hero?.mobileImageUrl||HERO_IMAGE;const heroPrimaryHref=hero?.primaryActionValue||'/order-by-date';const heroSecondaryHref=hero?.secondaryActionValue||'/category';const primary={left:`${hero?.primaryPosLeft??17.6}%`,top:`${hero?.primaryPosTop??35.8}%`,width:`${hero?.primaryPosWidth??35}%`,height:`${hero?.primaryPosHeight??6.7}%`};const secondary={left:`${hero?.secondaryPosLeft??53.1}%`,top:`${hero?.secondaryPosTop??35.8}%`,width:`${hero?.secondaryPosWidth??30.4}%`,height:`${hero?.secondaryPosHeight??6.4}%`};return <div>
<section className="relative w-full"><div className="relative w-full" style={{aspectRatio:'1024 / 1536'}}><Image src={heroImageSrc} alt="Outdoor tent event in Greenville, SC" fill priority sizes="100vw" className="object-cover" style={{objectPosition:`${(hero?.focalX??.5)*100}% ${(hero?.focalY??.5)*100}%`}}/><button type="button" onClick={()=>{trackEvent('hero_check_date_click');router.push(heroPrimaryHref)}} aria-label="Check event date" className="absolute rounded-md" style={primary}/><Link href={heroSecondaryHref} aria-label="Browse rentals" className="absolute rounded-md" style={secondary}/></div></section>
<section className="px-4 py-6"><h2 className="text-xl font-bold text-dark mb-4">{content?.shopCategoryHeading||'Shop by Category'}</h2><div className="grid grid-cols-2 gap-3">{categories.map(cat=><Link key={cat.slug} href={cat.href} className="relative block rounded-xl overflow-hidden bg-gray-100 aspect-square">{cat.image&&<Image src={cat.image} alt={cat.name} fill sizes="50vw" className="object-cover"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent"/><span className="absolute bottom-2 left-2 right-2 text-white font-semibold text-sm">{cat.name}</span></Link>)}</div><Link href="/category" className="block w-full text-center border-2 border-secondary text-secondary font-bold py-3 rounded-lg mt-4">VIEW ALL RENTALS</Link></section>
<section className="bg-secondary/10 border-y border-secondary/20 px-4 py-6 text-center"><h2 className="text-lg font-bold">Planning an Event?</h2><p className="text-sm text-body mb-4">Choose your event date to see what's available.</p><Link href="/order-by-date" className="block bg-secondary text-white font-bold py-4 rounded-lg">SELECT EVENT DATE</Link></section>
{bounceItems.length>0&&<RentalRow title="Bounce Houses & Water Slides" items={bounceItems} href="/category/bounce-house-rentals"/>}{popularItems.length>0&&<RentalRow title="Popular Rentals" items={popularItems}/>} 
{packages.length>0&&<section className="bg-pink-50 py-8"><div className="px-4"><h2 className="text-xl font-bold">Wedding & Event Packages</h2><p className="text-sm text-body mt-1">All-in-one packages for weddings, ceremonies, and celebrations.</p></div><div className="flex gap-3 overflow-x-auto px-4 py-4">{packages.map(pkg=><Link key={pkg.id} href={`/wedding-packages?package=${pkg.id}`} className="flex-shrink-0 w-[72%] bg-white rounded-xl border overflow-hidden"><div className="relative aspect-[4/3]">{pkg.image?<Image src={pkg.image} alt={pkg.name} fill sizes="72vw" className="object-cover"/>:<div className="absolute inset-0 bg-gray-100"/>}</div><div className="p-3"><p className="font-medium text-sm">{pkg.name}</p><p className="font-bold">{formatCurrency(pkg.price)}</p><p className="text-xs text-body">Up to {pkg.guests} guests</p></div></Link>)}</div><div className="px-4"><Link href="/wedding-packages" className="block text-center border-2 border-secondary text-secondary font-bold py-3 rounded-lg">VIEW ALL WEDDING PACKAGES</Link></div></section>}
<section className="px-4 py-8"><DesignYourEventCTA source="mobile_home"/></section>
<section className="bg-primary/20 py-8 px-4"><h2 className="text-xl font-bold text-center mb-6">Renting Is Easy</h2><div className="grid grid-cols-3 text-center"><div>📅<p className="text-xs font-medium mt-2">Pick Your Date</p></div><div>🛒<p className="text-xs font-medium mt-2">Choose Rentals</p></div><div>🚚<p className="text-xs font-medium mt-2">We Deliver</p></div></div></section>
<ReviewCarousel/>
<section className="relative w-full h-[45vh]">{weddingImage?<Image src={weddingImage} alt="Wedding rentals" fill sizes="100vw" className="object-cover"/>:<div className="absolute inset-0 bg-gray-200"/>}<div className="absolute inset-0 bg-black/40 flex flex-col items-center justify-center text-center px-6"><h2 className="text-white text-xl font-bold">Planning a Wedding or Large Event?</h2><p className="text-white/90 text-sm my-3">Explore our wedding rental packages.</p><Link href="/weddings" className="bg-white text-dark font-bold px-6 py-3 rounded-lg">VIEW WEDDING RENTALS</Link></div></section>
<section className="bg-gray-50 py-6 px-4 grid grid-cols-3 gap-2 text-center text-xs font-medium"><div>🏠<p>Local & Family Owned</p></div><div>✨<p>Clean, Quality Equipment</p></div><div>🚚<p>Delivery & Setup Available</p></div></section>
<section className="py-8 px-4 text-center"><p className="text-[#E07B00] text-xs font-bold uppercase">A Complete Solution</p><h2 className="text-lg font-bold my-2">Full-Service Event Planning</h2><p className="text-sm text-body mb-4">We plan it and provide it, so there is no need to hire a separate event planner.</p><Link href="/event-planning" className="btn-primary inline-block px-6 py-3">LEARN ABOUT EVENT PLANNING</Link></section>
<section className="py-8 px-4 text-center"><h2 className="text-lg font-bold mb-4">Watch Us on YouTube</h2><div className="relative aspect-video rounded-xl overflow-hidden"><YouTubeFacade videoId="LWQvMclQea4" title="Friendly Party Rental" className="absolute inset-0"/></div></section>{seoSection}</div>}
function RentalRow({title,items,href}:{title:string;items:MobilePopularItem[];href?:string}){return <section className="py-6"><h2 className="text-xl font-bold px-4 mb-4">{title}</h2><div className="flex gap-3 overflow-x-auto px-4">{items.map(item=><Link key={item.id} href={item.slug?`/items/${item.slug}`:'#'} className="flex-shrink-0 w-[72%] bg-white rounded-xl border overflow-hidden"><div className="relative aspect-[4/3]">{item.picture?<Image src={item.picture} alt={item.name} fill sizes="72vw" className="object-cover"/>:<div className="absolute inset-0 flex items-center justify-center bg-gray-100"><ImageOff/></div>}</div><div className="p-3"><p className="font-medium text-sm truncate">{item.name}</p><p className="font-bold text-sm">From {formatCurrency(item.cost)}</p></div></Link>)}</div>{href&&<Link href={href} className="block mx-4 mt-4 text-center border-2 border-secondary text-secondary font-bold py-3 rounded-lg">VIEW ALL</Link>}</section>}
