import Link from 'next/link'

export default function NycHomeSeo() {
  return <div className="mt-8 space-y-8">
    <div><h2 className="text-xl font-bold text-dark mb-3">Tent Rentals in Riverdale & Lower Westchester</h2><p className="text-body text-sm">Compare <Link href="/category/tent-rentals" prefetch={false} className="underline">pole tents, frame tents and canopies</Link> for weddings, graduations, backyard parties, corporate events and community celebrations. Choose a tent around guest count, seating, serving space, surface and access, then have the NYC team confirm the final installation requirements.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Table & Chair Rentals</h2><p className="text-body text-sm">Browse <Link href="/category/table-chair-rentals" prefetch={false} className="underline">banquet tables, round tables, cocktail tables, folding chairs, resin chairs and Chiavari chairs</Link> for events across Riverdale, the Northwest Bronx and Lower Westchester. Check the <Link href="/service-area#delivery-estimate" prefetch={false} className="underline">delivery fee for your event ZIP code</Link> while planning.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Bounce Houses & Water Slides</h2><p className="text-body text-sm">Explore <Link href="/category/bounce-house-rentals" prefetch={false} className="underline">bounce houses and water slides</Link>, plus concessions, yard games, generators and event add-ons. Review the item page for setup space, access, power, water and anchoring requirements before checkout.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Wedding Rentals</h2><p className="text-body text-sm">Compare <Link href="/weddings#packages" prefetch={false} className="underline">wedding packages</Link>, tents, tables, chairs, linens, lighting, dance floors and reception equipment. Use the event-layout tools to explore your setup, then have the NYC team confirm availability and site requirements.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Riverdale, Northwest Bronx & Lower Westchester Delivery</h2><p className="text-body text-sm">Friendly Party Rental NYC serves Riverdale, Fieldston, Kingsbridge, selected Northwest Bronx ZIP codes, Yonkers, Mount Vernon, New Rochelle, Bronxville, Eastchester, Tuckahoe and Pelham. <Link href="/service-area" prefetch={false} className="underline">Review the service area and ZIP-zone delivery estimator</Link>, or call <a href="tel:3158841498" className="underline">315-884-1498</a> for help.</p></div>
  </div>
}
