import Link from 'next/link'
import { NYC_SERVICE_AREAS } from '@/lib/nycServiceAreas'
import { NYC_LOCAL_PLANNING } from '@/lib/nycLocalPlanningResources'

export default function NycHomeSeo() {
  const verifiedAreas=NYC_SERVICE_AREAS.filter(area=>Boolean(NYC_LOCAL_PLANNING[area.slug]))
  return <div className="mt-8 space-y-8">
    <div><h2 className="text-xl font-bold text-dark mb-3">Tent Rentals in Riverdale, NY, the Bronx & Lower Westchester</h2><p className="text-body text-sm">Compare <Link href="/category/tent-rentals" prefetch={false} className="underline">pole tents, frame tents, and canopies</Link> for weddings, graduations, backyard parties, corporate events, and community celebrations. Choose a tent around guest count, seating, serving space, surface, access, and weather needs, then have our team confirm installation requirements for the site.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Table &amp; Chair Rentals in Riverdale, NY</h2><p className="text-body text-sm">Browse <Link href="/category/table-chair-rentals" prefetch={false} className="underline">banquet tables, round tables, cocktail tables, folding chairs, resin chairs, and Chiavari chairs</Link>. Check the <Link href="/service-area#delivery-estimate" prefetch={false} className="underline">delivery fee for your event ZIP code</Link> while planning your order.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Bounce House &amp; Water Slide Rentals in Riverdale, NY</h2><p className="text-body text-sm">Explore <Link href="/category/bounce-house-rentals" prefetch={false} className="underline">bounce houses and water slides</Link>, concessions, yard games, generators, and other event add-ons. Review each item page for setup space, power, water, and other requirements before checkout.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Wedding Rentals in Riverdale, NY</h2><p className="text-body text-sm">Compare <Link href="/weddings#packages" prefetch={false} className="underline">wedding packages</Link>, tents, tables, chairs, linens, lighting, dance floors, ceremony pieces, and reception equipment, then confirm availability and site requirements with the NYC / Downstate team.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Rentals &amp; Planning for Birthdays, Graduations, Weddings &amp; Business Events</h2><p className="text-body text-sm">Start with the event type when you need more than a single rental item. Explore <Link href="/graduation-rentals" prefetch={false} className="underline">graduation party rentals</Link>, <Link href="/event-planning/private-parties" prefetch={false} className="underline">private party planning</Link>, <Link href="/event-planning/corporate-events" prefetch={false} className="underline">corporate event planning</Link>, <Link href="/event-planning/wedding-coordination" prefetch={false} className="underline">wedding coordination</Link>, and <Link href="/event-planning/festivals-fundraisers" prefetch={false} className="underline">festival and fundraiser planning</Link>.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">2D &amp; 3D Event Layout Planner</h2><p className="text-body text-sm">Before choosing final quantities, use the <Link href="/design-your-event" prefetch={false} className="underline">2D and 3D event layout planner</Link> to test tent placement, tables, chairs, dance-floor space and other rental equipment. The visual layout helps you plan the space; NYC checkout still confirms the live availability, delivery, tax and deposit for your event date.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Linens &amp; Concession Rentals in Riverdale, NY</h2><p className="text-body text-sm">Finish the event with <Link href="/category/linen-rentals" prefetch={false} className="underline">table linens and chair covers</Link> plus <Link href="/category/concession-machine-rentals" prefetch={false} className="underline">popcorn, cotton candy, snow-cone and other concession equipment</Link>. Pair these add-ons with tables, chairs, lighting and party packages while checking the same event date.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Riverdale, Bronx &amp; Lower Westchester Delivery</h2><p className="text-body text-sm">Friendly Party Rental NYC serves Riverdale, Fieldston, Kingsbridge, selected Bronx ZIP codes, Yonkers, Mount Vernon, New Rochelle, Bronxville, Tuckahoe, Eastchester, Pelham, and nearby approved areas. <Link href="/service-area" prefetch={false} className="underline">Review the service area and delivery fee checker</Link>, or call <a href="tel:+13158841498" className="underline">315-884-1498</a>.</p><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-sm">{verifiedAreas.map(area=><Link key={area.slug} href={area.href} prefetch={false} className="font-semibold text-blue-800 underline">Party rentals in {area.name}, NY</Link>)}</div></div>
  </div>
}
