import Link from 'next/link'

export default function NycHomeSeo() {
  return <div className="mt-8 space-y-8">
    <div><h2 className="text-xl font-bold text-dark mb-3">Tent Rentals in Riverdale, the Bronx & Lower Westchester</h2><p className="text-body text-sm">Compare <Link href="/category/tent-rentals" prefetch={false} className="underline">pole tents, frame tents, and canopies</Link> for weddings, graduations, backyard parties, corporate events, and community celebrations. Choose a tent around guest count, seating, serving space, surface, access, and weather needs, then have our team confirm installation requirements for the site.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Table &amp; Chair Rentals</h2><p className="text-body text-sm">Browse <Link href="/category/table-chair-rentals" prefetch={false} className="underline">banquet tables, round tables, cocktail tables, folding chairs, resin chairs, and Chiavari chairs</Link>. Check the <Link href="/service-area#delivery-estimate" prefetch={false} className="underline">delivery fee for your event ZIP code</Link> while planning your order.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Bounce Houses &amp; Water Slides</h2><p className="text-body text-sm">Explore <Link href="/category/bounce-house-rentals" prefetch={false} className="underline">bounce houses and water slides</Link>, concessions, yard games, generators, and other event add-ons. Review each item page for setup space, power, water, and other requirements before checkout.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Wedding Rentals</h2><p className="text-body text-sm">Compare <Link href="/weddings#packages" prefetch={false} className="underline">wedding packages</Link>, tents, tables, chairs, linens, lighting, dance floors, ceremony pieces, and reception equipment, then confirm availability and site requirements with the NYC / Downstate team.</p></div>
    <div><h2 className="text-xl font-bold text-dark mb-3">Riverdale, Bronx &amp; Lower Westchester Delivery</h2><p className="text-body text-sm">Friendly Party Rental NYC serves Riverdale, Fieldston, Kingsbridge, selected Bronx ZIP codes, Yonkers, Mount Vernon, New Rochelle, Bronxville, Tuckahoe, Eastchester, Pelham, and nearby approved areas. <Link href="/service-area" prefetch={false} className="underline">Review the service area and delivery fee checker</Link>, or call <a href="tel:+13158841498" className="underline">315-884-1498</a>.</p></div>
  </div>
}
