import Image from 'next/image'
import Link from 'next/link'
import { PLANNING_ORIGIN, planningFaqs, planningServices } from '@/lib/eventPlanning'
import PlanningInquiryForm from './PlanningInquiryForm'
import PlanningContactLinks from './PlanningContactLinks'
import PlanningPackages from './PlanningPackages'
import PlanningEstimator from './PlanningEstimator'
import DesignYourEventCTA from './DesignYourEventCTA'
import { NYC_SERVICE_AREA_SUMMARY } from '@/lib/nycServiceAreas'

type Service = (typeof planningServices)[number]
export default function PlanningPage({ service }: { service?: Service }) {
  const title = service?.title || 'Event Planning & Coordination in Riverdale, NY'
  const path = '/event-planning' + (service ? '/' + service.slug : '')
  const image = service?.image || '/images/event-planning/tent-patio-setup/image.png'
  const schema = { '@context': 'https://schema.org', '@type': 'Service', name: title, serviceType: service?.label || 'Event planning and coordination', url: PLANNING_ORIGIN + path, areaServed: { '@type': 'City', name: 'Riverdale' }, provider: { '@type': 'Organization', name: 'Friendly Party Rental NYC', url: PLANNING_ORIGIN, telephone: '+1-315-884-1498' } }
  return <div className="bg-slate-50 pb-20 md:pb-0" data-planning-page>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }}/>
    <section className="overflow-hidden bg-blue-950 text-white">
      <div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 md:grid-cols-[1.1fr_1fr] md:items-center md:gap-14 md:py-16 lg:px-8">
        <div><nav aria-label="Breadcrumb" className="mb-8 text-xs text-blue-100"><Link className="hover:underline" href="/">Home</Link><span className="mx-2">/</span>{service ? <><Link className="hover:underline" href="/event-planning">Event planning</Link><span className="mx-2">/</span><span>{service.label}</span></> : <span>Event planning</span>}</nav>
          <p className="mb-4 text-xs font-bold uppercase tracking-[0.2em] text-amber-300">Friendly Party Rental · Downstate New York</p>
          <h1 className="max-w-3xl text-4xl font-bold leading-tight tracking-tight md:text-5xl lg:text-6xl">{title}</h1>
          <p className="mt-6 max-w-xl text-lg leading-relaxed text-blue-100">{service?.summary || 'One team for your rentals, layout, vendors, setup and event-day coordination.'}</p>
          <a href="#event-estimator" className="mt-8 inline-flex min-h-12 items-center justify-center gap-3 rounded-xl bg-amber-300 px-6 py-4 text-center text-sm font-bold text-blue-950 shadow-lg transition hover:bg-amber-200">Build My Event Estimate <span aria-hidden="true">→</span></a>
          <p className="mt-3 text-xs text-blue-100">Explore photos, compare planning support and choose your rentals. No account needed.</p>
          <div className="mt-6"><PlanningContactLinks/></div>
        </div>
        <div className="relative"><div className="relative aspect-[5/4] overflow-hidden rounded-3xl border border-white/20"><Image src={image} alt={service?.alt || 'Outdoor tent and patio seating setup'} fill priority sizes="(max-width: 767px) 100vw, 46vw" className="object-cover"/></div><p className="mt-3 text-xs text-blue-100">Setup inspiration from our website gallery. Your layout and services are confirmed in your quote.</p></div>
      </div>
    </section>
    <div className="mx-auto max-w-7xl px-5 lg:px-8">
      <section className="py-12" aria-labelledby="event-types"><p className="text-xs font-bold uppercase tracking-widest text-blue-800">Start with your event</p><h2 id="event-types" className="mt-3 text-2xl font-bold text-slate-950">{service ? 'Explore our planning services' : 'What are you planning?'}</h2><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{planningServices.map(s => <Link key={s.slug} href={'/event-planning/' + s.slug} aria-current={service?.slug === s.slug ? 'page' : undefined} className="group min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white text-slate-900 shadow-sm transition hover:border-blue-400 hover:shadow-md"><div className="relative aspect-[3/2] overflow-hidden"><Image src={s.image} alt={s.alt} fill sizes="(max-width: 767px) 45vw, 280px" className="object-cover transition-transform group-hover:scale-105 motion-reduce:transition-none"/></div><div className="flex min-h-20 items-center justify-between gap-2 p-4 text-xs font-bold sm:text-sm"><span>{s.label}</span><span aria-hidden="true" className="text-blue-700">→</span></div></Link>)}</div></section>
      <PlanningEstimator initialType={service?.type}/>
      {service ? <section className="border-t border-slate-200 py-12"><h2 className="text-3xl font-bold text-slate-950">A plan built around your {service.type.toLowerCase()}</h2><p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-600">{service.intro}</p><div className="mt-8 grid gap-6 md:grid-cols-3">{service.sections.map(s => <article key={s.title} className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="text-lg font-bold text-slate-950">{s.title}</h3><p className="mt-4 text-sm leading-7 text-slate-600">{s.text}</p></article>)}</div><div className="mt-8 rounded-2xl bg-blue-50 p-6"><h3 className="font-bold text-blue-950">What to bring to your consultation</h3><ul className="mt-4 space-y-3 text-sm text-blue-950">{service.checklist.map(t => <li key={t}>✓ {t}</li>)}</ul></div></section> : <section className="grid gap-8 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 md:grid-cols-2 md:p-10"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-800">Planning + rentals under one roof</p><h2 className="mt-4 text-3xl font-bold text-slate-950">Less coordinating.<br/>More enjoying your event.</h2><p className="mt-5 leading-7 text-slate-600">Your layout, equipment and timeline should work together. Discuss your tents, tables, chairs, linens and lighting with the same team helping you plan the event. We will define the services, responsibilities and on-site hours before you book.</p><Link href="/category" className="mt-5 inline-block py-2 font-semibold text-blue-800 underline">Explore our rental catalog →</Link></div><div className="space-y-6">{[['Tell us what you are planning','Share your date, guest count, location and what you have already arranged.'],['Get a defined scope and quote','Review your planning support, rental equipment, logistics and fees together.'],['Know who is handling what','Confirm the timeline, vendor contacts and event-day responsibilities with your team.']].map(([heading,text], i) => <div key={heading} className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-50 font-bold text-blue-800">{i+1}</span><div><h3 className="font-bold text-slate-950">{heading}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div></div>)}</div></section>}
      <PlanningPackages/>
      <section className="mb-14 flex flex-col gap-6 rounded-3xl bg-blue-50 p-6 md:flex-row md:items-center md:justify-between md:p-9"><div className="max-w-2xl"><h2 className="text-2xl font-bold text-blue-950">Start with a visual layout</h2><p className="mt-3 leading-7 text-slate-600">Try arranging tents, tables and chairs in our event designer. Bring the layout to your consultation. A design is a starting point, not confirmation of fit or availability.</p></div><DesignYourEventCTA source="event_planning_page" label="Create My Layout" variant="primary" className="shrink-0"/></section>
      <section id="planning-inquiry" className="scroll-mt-28 grid gap-8 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 md:grid-cols-[.75fr_1.25fr] md:p-10"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-800">Let’s talk about your event</p><h2 className="mt-4 text-3xl font-bold text-slate-950">Tell us about your event</h2><p className="mt-5 leading-7 text-slate-600">You do not need to have every detail figured out. Tell us where you are in the process and what you need help with.</p><p className="mt-6 font-bold text-blue-950">Prefer a conversation?</p><a className="mt-2 inline-block text-xl font-bold text-blue-800 underline" href="tel:+13158841498">315-884-1498</a><p className="mt-6 text-sm leading-6 text-slate-500">Inquiries are reviewed during office hours. Sending a request does not reserve your date.</p><p className="mt-6 text-sm leading-6 text-slate-600">Serving {NYC_SERVICE_AREA_SUMMARY}. Location and delivery fees are confirmed in your quote.</p></div><PlanningInquiryForm initialType={service?.type}/></section>
      <section className="mx-auto max-w-4xl py-14"><h2 className="mb-6 text-3xl font-bold text-slate-950">Event planning questions</h2><div className="divide-y divide-slate-200">{planningFaqs.map(faq => <details key={faq.question} className="py-5"><summary className="cursor-pointer pr-4 font-bold text-slate-900">{faq.question}</summary><p className="mt-4 text-sm leading-7 text-slate-600">{faq.answer}</p></details>)}</div></section>
    </div>
    <div data-planning-mobile-actions className="fixed inset-x-0 bottom-[calc(60px+env(safe-area-inset-bottom))] z-40 border-t border-white/20 bg-blue-950 p-2 shadow-xl md:hidden"><PlanningContactLinks compact/></div>
  </div>
}
