import Link from 'next/link'
export default function ScHomeSeo(){
 return <div className="mt-8 space-y-8">
  <div><h2 className="text-xl font-bold text-dark mb-3">Tent Rentals in Riverdale &amp; Lower Westchester</h2><p className="text-body text-sm">Compare <Link href="/category/tent-rentals" prefetch={false} className="underline">pole tents, frame tents and canopies</Link> for weddings, graduations, backyard parties, corporate events and community celebrations. Choose a tent around guest count, seating, serving space, surface and access, then have our NYC / Downstate team confirm installation requirements for the site.</p></div>
  <div><h2 className="text-xl font-bold text-dark mb-3">Table &amp; Chair Rentals</h2><p className="text-body text-sm">Browse <Link href="/category/table-chair-rentals" prefetch={false} className="underline">banquet tables, round tables, cocktail tables, folding chairs, resin chairs and Chiavari chairs</Link> for Riverdale, Bronx and Lower Westchester events. Check the <Link href="/service-area#delivery-estimate" prefetch={false} className="underline">ZIP-based delivery estimate</Link> while planning your order.</p></div>
  <div><h2 className="text-xl font-bold text-dark mb-3">Bounce Houses &amp; Water Slides</h2><p className="text-body text-sm">Explore <Link href="/category/bounce-house-rentals" prefetch={false} className="underline">bounce houses and water slides</Link>, plus concessions, yard games, generators and event add-ons. Review each item for setup space, power, water and access requirements before checkout.</p></div>
  <div><h2 className="text-xl font-bold text-dark mb-3">Wedding Rentals</h2><p className="text-body text-sm">Compare <Link href="/weddings#packages" prefetch={false} className="underline">wedding packages</Link>, tents, tables, chairs, linens, lighting, dance floors and reception equipment. Our NYC / Downstate team confirms availability, site requirements and final pricing.</p></div>
  <div><h2 className="text-xl font-bold text-dark mb-3">Riverdale, the Bronx &amp; Lower Westchester Delivery</h2><p className="text-body text-sm">Friendly Party Rental NYC serves Riverdale, Fieldston, Kingsbridge, Yonkers, Mount Vernon, New Rochelle and selected Lower Westchester communities. Travel fees are separate from rental prices. <Link href="/service-area" prefetch={false} className="underline">Review the service area and delivery estimator</Link>, or call <a href="tel:3158841498" className="underline">315-884-1498</a>.</p></div>
 </div>
}
