'use client'

import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'

interface AutomaticMessage {
  id: string
    name: string
      daysToSend: number
        sendOption: string
          fromEmail?: string
            subject: string
              content: string
                filter: string
                  enabled: boolean
                  }

                  export default function AutomaticMessagesPage() {
                    const [messages, setMessages] = useState<AutomaticMessage[]>([])
                      const [editingId, setEditingId] = useState<string | null>(null)
                        const [form, setForm] = useState<Partial<AutomaticMessage>>({})

                          useEffect(() => {
                              fetch('/api/admin/automatic-messages')
                                    .then((r) => r.json())
                                          .then((d) => setMessages(d.messages || []))
                                            }, [])

                                              const startEdit = (m: AutomaticMessage) => {
                                                  setEditingId(m.id)
                                                      setForm(m)
                                                        }

                                                          const cancelEdit = () => {
                                                              setEditingId(null)
                                                                  setForm({})
                                                                    }

                                                                      const handleSave = async () => {
                                                                          const res = await fetch('/api/admin/automatic-messages', {
                                                                                method: 'PATCH',
                                                                                      headers: { 'Content-Type': 'application/json' },
                                                                                            body: JSON.stringify(form),
                                                                                                })
                                                                                                    if (res.ok) {
                                                                                                          const { message } = await res.json()
                                                                                                                setMessages(messages.map((m) => (m.id === message.id ? message : m)))
                                                                                                                      toast.success('Message updated')
                                                                                                                            cancelEdit()
                                                                                                                                } else {
                                                                                                                                      toast.error('Failed to update message')
                                                                                                                                          }
                                                                                                                                            }
                                                                                                                                            
                                                                                                                                              const handleToggleEnabled = async (m: AutomaticMessage) => {
                                                                                                                                                  const res = await fetch('/api/admin/automatic-messages', {
                                                                                                                                                        method: 'PATCH',
                                                                                                                                                              headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                    body: JSON.stringify({ id: m.id, enabled: !m.enabled }),
                                                                                                                                                                        })
                                                                                                                                                                            if (res.ok) {
                                                                                                                                                                                  setMessages(messages.map((x) => (x.id === m.id ? { ...x, enabled: !x.enabled } : x)))
                                                                                                                                                                                      }
                                                                                                                                                                                        }
                                                                                                                                                                                        
                                                                                                                                                                                          return (
                                                                                                                                                                                              <div className="p-4">
                                                                                                                                                                                                    <h1 className="text-xl font-bold text-dark mb-2">Automatic Messages</h1>
                                                                                                                                                                                                          <p className="text-sm text-body mb-6">
                                                                                                                                                                                                                  Manage the automatic email messages sent to customers. Note: editing content here updates this record, but the live sending logic for these emails is still managed in code - a developer needs to wire a message before edits here change what customers actually receive.
                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                              <div className="bg-white rounded shadow divide-y">
                                                                                                                                                                                                                                      {messages.map((m) => (
                                                                                                                                                                                                                                                <div key={m.id} className="p-4">
                                                                                                                                                                                                                                                            {editingId === m.id ? (
                                                                                                                                                                                                                                                                          <div className="grid gap-3">
                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-2 gap-3">
                                                                                                                                                                                                                                                                                                            <input placeholder="Name" value={form.name || ''} onChange={(e) => setForm({ ...form, name: e.target.value })} className="border rounded px-3 py-2 text-sm" />
                                                                                                                                                                                                                                                                                                                              <input placeholder="Days to Send" type="number" value={form.daysToSend ?? 0} onChange={(e) => setForm({ ...form, daysToSend: parseInt(e.target.value) })} className="border rounded px-3 py-2 text-sm" />
                                                                                                                                                                                                                                                                                                                                                <select value={form.sendOption || ''} onChange={(e) => setForm({ ...form, sendOption: e.target.value })} className="border rounded px-3 py-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                    <option value="Before Order Starts">Before Order Starts</option>
                                                                                                                                                                                                                                                                                                                                                                                        <option value="After Order Ends">After Order Ends</option>
                                                                                                                                                                                                                                                                                                                                                                                                            <option value="On Order Placed">On Order Placed</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="N/A - Incomplete Order">N/A - Incomplete Order</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select value={form.filter || ''} onChange={(e) => setForm({ ...form, filter: e.target.value })} className="border rounded px-3 py-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="Active Only">Active Only</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="Incomplete">Incomplete</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="All">All</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input placeholder="From Email (optional)" value={form.fromEmail || ''} onChange={(e) => setForm({ ...form, fromEmail: e.target.value })} className="border rounded px-3 py-2 text-sm col-span-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input placeholder="Subject Line" value={form.subject || ''} onChange={(e) => setForm({ ...form, subject: e.target.value })} className="border rounded px-3 py-2 text-sm col-span-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea placeholder="Content" value={form.content || ''} onChange={(e) => setForm({ ...form, content: e.target.value })} className="border rounded px-3 py-2 text-sm w-full" rows={8} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={handleSave} className="bg-blue-600 text-white px-4 py-2 rounded text-sm">Save</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={cancelEdit} className="border px-4 py-2 rounded text-sm">Cancel</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center justify-between gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="font-medium text-sm">{m.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-xs text-body">Days to send: {m.daysToSend} - {m.sendOption} - Filter: {m.filter}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-xs text-body">Subject: {m.subject}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="flex items-center gap-1 text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="checkbox" checked={m.enabled} onChange={() => handleToggleEnabled(m)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Enabled
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => startEdit(m)} className="border px-3 py-1 rounded text-sm">Edit</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
