'use client'

import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'

interface LoyaltyType {
  id: string
    name: string
      type: string
        amount: number
          isActive: boolean
          }

          export default function LoyaltyCreditTypesPage() {
            const [types, setTypes] = useState<LoyaltyType[]>([])
              const [loading, setLoading] = useState(true)
                const [newName, setNewName] = useState('')
                  const [newType, setNewType] = useState('Credit')
                    const [newAmount, setNewAmount] = useState('0')

                      const load = async () => {
                          const res = await fetch('/api/admin/loyalty-credit-types')
                              const data = await res.json()
                                  setTypes(data.types || [])
                                      setLoading(false)
                                        }

                                          useEffect(() => { load() }, [])

                                            const addType = async () => {
                                                if (!newName.trim()) return
                                                    const res = await fetch('/api/admin/loyalty-credit-types', {
                                                          method: 'POST',
                                                                headers: { 'Content-Type': 'application/json' },
                                                                      body: JSON.stringify({ name: newName, type: newType, amount: newAmount }),
                                                                          })
                                                                              if (res.ok) {
                                                                                    toast.success('Added')
                                                                                          setNewName('')
                                                                                                setNewAmount('0')
                                                                                                      load()
                                                                                                          } else {
                                                                                                                toast.error('Failed to add')
                                                                                                                    }
                                                                                                                      }
                                                                                                                      
                                                                                                                        const toggleActive = async (t: LoyaltyType) => {
                                                                                                                            const res = await fetch('/api/admin/loyalty-credit-types', {
                                                                                                                                  method: 'PATCH',
                                                                                                                                        headers: { 'Content-Type': 'application/json' },
                                                                                                                                              body: JSON.stringify({ id: t.id, isActive: !t.isActive }),
                                                                                                                                                  })
                                                                                                                                                      if (res.ok) {
                                                                                                                                                            toast.success('Updated')
                                                                                                                                                                  load()
                                                                                                                                                                      }
                                                                                                                                                                        }
                                                                                                                                                                        
                                                                                                                                                                          const removeType = async (id: string) => {
                                                                                                                                                                              if (!confirm('Remove this loyalty/credit type?')) return
                                                                                                                                                                                  const res = await fetch(`/api/admin/loyalty-credit-types?id=${id}`, { method: 'DELETE' })
                                                                                                                                                                                      if (res.ok) {
                                                                                                                                                                                            toast.success('Removed')
                                                                                                                                                                                                  load()
                                                                                                                                                                                                      }
                                                                                                                                                                                                        }
                                                                                                                                                                                                        
                                                                                                                                                                                                          if (loading) return <div className="p-4">Loading...</div>
                                                                                                                                                                                                          
                                                                                                                                                                                                            return (
                                                                                                                                                                                                                <div className="p-4">
                                                                                                                                                                                                                      <h1 className="text-xl font-bold text-dark mb-2">Loyalty & Credit Types</h1>
                                                                                                                                                                                                                            <p className="text-sm text-gray-600 mb-6">Manage account credit and loyalty point types that can be applied to customer accounts or orders.</p>
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                  <div className="bg-white rounded shadow p-4 mb-4">
                                                                                                                                                                                                                                          <div className="flex gap-2">
                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                            value={newName}
                                                                                                                                                                                                                                                                                        onChange={(e) => setNewName(e.target.value)}
                                                                                                                                                                                                                                                                                                    placeholder="Name (e.g. Referral Credit)"
                                                                                                                                                                                                                                                                                                                className="border rounded px-3 py-2 text-sm flex-1"
                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                    <select value={newType} onChange={(e) => setNewType(e.target.value)} className="border rounded px-3 py-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                <option value="Credit">Credit</option>
                                                                                                                                                                                                                                                                                                                                                            <option value="Points">Points</option>
                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                                                                                                                                                                        value={newAmount}
                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setNewAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Amount"
                                                                                                                                                                                                                                                                                                                                                                                                                                            className="border rounded px-3 py-2 text-sm w-28"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={addType} className="bg-admin-dark text-white px-4 py-2 rounded text-sm">Add</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-white rounded shadow divide-y">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {types.map((t) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={t.id} className="flex items-center justify-between px-4 py-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-sm">{t.name} - {t.type} - {t.amount}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="flex items-center gap-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="checkbox" checked={t.isActive} onChange={() => toggleActive(t)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Active
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => removeType(t.id)} className="text-red-600 text-sm">Delete</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {types.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="px-4 py-3 text-sm text-gray-500">No loyalty/credit types yet.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
