-- Add ERS-parity override fields to Order and creditStatus to Customer
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "locationName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "generalDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "overrideTravelFee" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "overrideDepositAmount" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "overrideTaxAmount" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "miscellaneousFees" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "creditStatus" TEXT NOT NULL DEFAULT 'good';
