'use client'

import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'

export default function OrderOptionsPage() {
  const [loading, setLoading] = useState(true)
    const [saving, setSaving] = useState(false)

      const [requireDamageWaiver, setRequireDamageWaiver] = useState(false)
        const [allowOnlineOrders, setAllowOnlineOrders] = useState(true)
          const [autoAcceptOrders, setAutoAcceptOrders] = useState(true)
            const [defaultDepositPercent, setDefaultDepositPercent] = useState('25')
              const [allowPartialPayments, setAllowPartialPayments] = useState(true)
                const [requirePhoneNumber, setRequirePhoneNumber] = useState(true)

                  const [minimumNoticeHours, setMinimumNoticeHours] = useState('24')
                    const [cancellationWindowHours, setCancellationWindowHours] = useState('48')

                      const load = async () => {
                          const res = await fetch('/api/admin/order-settings')
                              const data = await res.json()
                                  const s = data.settings
                                      if (s) {
                                            setRequireDamageWaiver(s.requireDamageWaiver)
                                                  setAllowOnlineOrders(s.allowOnlineOrders)
                                                        setAutoAcceptOrders(s.autoAcceptOrders)
                                                              setDefaultDepositPercent(String(s.defaultDepositPercent))
                                                                    setAllowPartialPayments(s.allowPartialPayments)
                                                                          setRequirePhoneNumber(s.requirePhoneNumber)
                                                                                setMinimumNoticeHours(String(s.minimumNoticeHours))
                                                                                      setCancellationWindowHours(String(s.cancellationWindowHours))
                                                                                          }
                                                                                              setLoading(false)
                                                                                                }

                                                                                                  useEffect(() => { load() }, [])

                                                                                                    const save = async () => {
                                                                                                        setSaving(true)
                                                                                                            const res = await fetch('/api/admin/order-settings', {
                                                                                                                  method: 'PATCH',
                                                                                                                        headers: { 'Content-Type': 'application/json' },
                                                                                                                              body: JSON.stringify({
                                                                                                                                      requireDamageWaiver,
                                                                                                                                              allowOnlineOrders,
                                                                                                                                                      autoAcceptOrders,
                                                                                                                                                              defaultDepositPercent,
                                                                                                                                                                      allowPartialPayments,
                                                                                                                                                                              requirePhoneNumber,
                                                                                                                                                                                      minimumNoticeHours,
                                                                                                                                                                                              cancellationWindowHours,
                                                                                                                                                                                                    }),
                                                                                                                                                                                                        })
                                                                                                                                                                                                            setSaving(false)
                                                                                                                                                                                                                if (res.ok) {
                                                                                                                                                                                                                      toast.success('Order settings saved')
                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                toast.error('Failed to save')
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                        if (loading) return <div className="p-4">Loading...</div>
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                              <div className="p-4">
                                                                                                                                                                                                                                                    <h1 className="text-xl font-bold text-dark mb-2">Order Options and Misc Order Settings</h1>
                                                                                                                                                                                                                                                          <p className="text-sm text-gray-600 mb-6">Configure default behavior for how orders are placed, accepted, and paid for.</p>
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                <div className="bg-white rounded shadow p-4 max-w-md mb-4">
                                                                                                                                                                                                                                                                        <div className="bg-admin-dark text-white px-3 py-2 -mx-4 -mt-4 mb-4 rounded-t font-medium text-sm">Order Options</div>
                                                                                                                                                                                                                                                                                <div className="space-y-3">
                                                                                                                                                                                                                                                                                          <label className="flex items-center gap-2 text-sm">
                                                                                                                                                                                                                                                                                                      <input type="checkbox" checked={requireDamageWaiver} onChange={(e) => setRequireDamageWaiver(e.target.checked)} />
                                                                                                                                                                                                                                                                                                                  Require damage waiver on all orders
                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                      <label className="flex items-center gap-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                  <input type="checkbox" checked={allowOnlineOrders} onChange={(e) => setAllowOnlineOrders(e.target.checked)} />
                                                                                                                                                                                                                                                                                                                                                              Allow online orders
                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                  <label className="flex items-center gap-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                              <input type="checkbox" checked={autoAcceptOrders} onChange={(e) => setAutoAcceptOrders(e.target.checked)} />
                                                                                                                                                                                                                                                                                                                                                                                                          Automatically accept new orders
                                                                                                                                                                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="flex items-center gap-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="checkbox" checked={allowPartialPayments} onChange={(e) => setAllowPartialPayments(e.target.checked)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Allow partial payments and deposits
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="flex items-center gap-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input type="checkbox" checked={requirePhoneNumber} onChange={(e) => setRequirePhoneNumber(e.target.checked)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Require phone number at checkout
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-medium mb-1">Default deposit percent</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="number" value={defaultDepositPercent} onChange={(e) => setDefaultDepositPercent(e.target.value)} className="border rounded px-3 py-2 text-sm w-full" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-white rounded shadow p-4 max-w-md mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-admin-dark text-white px-3 py-2 -mx-4 -mt-4 mb-4 rounded-t font-medium text-sm">Misc Order Settings</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-medium mb-1">Minimum advance notice required in hours</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="number" value={minimumNoticeHours} onChange={(e) => setMinimumNoticeHours(e.target.value)} className="border rounded px-3 py-2 text-sm w-full" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm font-medium mb-1">Cancellation window in hours before event</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input type="number" value={cancellationWindowHours} onChange={(e) => setCancellationWindowHours(e.target.value)} className="border rounded px-3 py-2 text-sm w-full" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={save} disabled={saving} className="bg-admin-dark text-white px-4 py-2 rounded text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {saving ? 'Saving...' : 'Save'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
