const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const read=p=>fs.readFileSync(p,'utf8')
test('Riverdale service-area redesign stays truthful and delivery-only',()=>{
 const page=read('app/(public)/service-area/page.tsx')
 const dir=read('components/public/ServiceAreaDirectory.tsx')
 assert.match(page,/11 listed communities/)
 assert.doesNotMatch(page,/34 nearby|35 listed/)
 assert.match(page,/Delivery-only storefront/)
 assert.match(page,/No customer warehouse pickup/)
 assert.match(page,/not presented as a Riverdale event/)
 assert.match(page,/NYC_PRIORITY_AREAS/)
 assert.doesNotMatch(page,/330 Costello|Minoa|Syracuse|Central New York/)
 assert.match(dir,/NYC_SERVICE_AREAS/)
 assert.match(dir,/Try Yonkers or 10471/)
 assert.match(dir,/\{area\.name\}, NY</)
 assert.doesNotMatch(dir,/Greer|29650|, SC</)
 assert.match(dir,/315-884-1498/)
})
