const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
test('NYC standalone tent pages keep the rental photo and add the real RentSketch layout preview',()=>{
  const source=fs.readFileSync('app/(public)/items/[...slug]/page.tsx','utf8')
  assert.match(source,/See what the \{item\.name\} looks like/)
  assert.match(source,/\/api\/item-image\//)
  assert.match(source,/DesignYourEventCTA/)
  assert.match(source,/See This Tent in a Layout/)
  assert.match(source,/productType=\{isInflatable \? 'inflatable' : 'tent'\}/)
})
