const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
test('NYC product preview CTA launches RentSketch when tenant is live and retains a photo fallback',()=>{
  const cta=fs.readFileSync('components/public/DesignYourEventCTA.tsx','utf8')
  const launcher=fs.readFileSync('components/public/DesignYourEventLauncher.tsx','utf8')
  assert.match(cta,/NYC_RENTSKETCH_TENANT/)
  assert.match(cta,/productType/)
  assert.match(cta,/open-design-your-event/)
  assert.match(cta,/Rental tent photo/)
  assert.match(cta,/\/api\/item-image\//)
  assert.match(launcher,/focus',productType/)
  assert.match(launcher,/inflatable-preview/)
})
