const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
test('tent-specific previews use RentSketch when NYC tenant exists and photo fallback otherwise',()=>{
  const card=fs.readFileSync('components/public/ItemCard.tsx','utf8')
  const cta=fs.readFileSync('components/public/DesignYourEventCTA.tsx','utf8')
  assert.match(card,/DesignYourEventCTA source="tent_item_card"/)
  assert.match(card,/label="View Tent Photo"/)
  assert.doesNotMatch(card,/See This Tent in a Layout/)
  assert.doesNotMatch(card,/open-design-your-event.*tent_item_card/)
  assert.match(cta,/if \(\(tent \|\| tentSlug\) && !NYC_RENTSKETCH_TENANT\)/)
  assert.match(cta,/Rental tent photo/)
  assert.match(cta,/\/api\/item-image\//)
  assert.match(cta,/productType/)
  assert.match(cta,/open-design-your-event/)
})
