const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
test('NYC tent cards launch RentSketch when configured and retain a photo fallback when it is not',()=>{
  const card=fs.readFileSync('components/public/ItemCard.tsx','utf8')
  const cta=fs.readFileSync('components/public/DesignYourEventCTA.tsx','utf8')
  assert.match(card,/DesignYourEventCTA source="tent_item_card"/)
  assert.match(card,/label="See This Tent in a Layout"/)
  assert.match(cta,/\(tent \|\| tentSlug\) && !NYC_RENTSKETCH_TENANT/)
  assert.match(cta,/Rental tent photo/)
  assert.match(cta,/View Tent Photo/)
  assert.match(cta,/return <button type="button" onClick=\{handleClick\}/)
})
