const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const read=p=>fs.readFileSync(p,'utf8')

test('SC abandoned checkout is captured without reserving inventory or enabling pickup',()=>{
  const schema=read('prisma/schema.prisma'), draft=read('app/api/checkout/draft/route.ts'), availability=read('lib/availability.ts')
  assert.match(schema,/checkoutDraftKey String\? @unique/)
  assert.match(schema,/checkoutStage String\?/)
  assert.match(draft,/status: 'incomplete'/)
  assert.match(draft,/deliveryType: 'delivery'/)
  assert.match(draft,/requireDeliveryMethod/)
  assert.doesNotMatch(draft,/usageCount: \{ increment: 1 \}/)
  assert.doesNotMatch(draft,/reserveExactTimeSlot/)
  assert.match(availability,/notIn: \['canceled', 'cancelled', 'draft', 'incomplete'\]/)
})

test('SC draft funnel advances through payment and verified completion',()=>{
  const details=read('app/(public)/checkout/page.tsx'), payment=read('app/(public)/checkout/payment/page.tsx'), checkout=read('app/api/checkout/route.ts'), payments=read('lib/payments.ts')
  assert.match(details,/checkout_draft_key/)
  assert.match(details,/stage: 'details_completed'/)
  assert.match(payment,/stage: 'payment_page'/)
  assert.match(payment,/removeItem\('checkout_draft_key'\)/)
  assert.match(checkout,/order\.status === 'incomplete'/)
  assert.match(checkout,/findInventoryShortfalls/)
  assert.match(checkout,/evaluateRentalRestrictions/)
  assert.match(checkout,/requireMatchingDeliveryFee/)
  assert.match(payments,/checkoutStage: 'completed'/)
  assert.match(payments,/checkoutCompletedAt: order\.checkoutCompletedAt \|\| new Date\(\)/)
})

test('SC recovery emails remain retryable and unfinished-only leads stay out of general marketing',()=>{
  const cron=read('app/api/cron/incomplete-orders/route.ts'), audience=read('lib/marketing/audience.ts')
  assert.match(cron,/retryableFailures/)
  assert.match(cron,/Missing\/failed SMTP must remain retryable/)
  assert.match(cron,/payment_page/)
  assert.match(cron,/gt: fourteenDaysAgo/)
  assert.match(audience,/marketingCustomerIds/)
  assert.match(audience,/!\['incomplete','draft'\]\.includes/)
})

test('SC lifecycle messages use Riverdale URLs and cancellation transition is automatic but non-blocking',()=>{
  const lifecycle=read('lib/orderLifecycleNotifications.ts'), orderRoute=read('app/api/orders/route.ts'), admin=read('app/api/admin/orders/\[id\]/route.ts')
  assert.match(lifecycle,/friendlypartyrentalsc\.com\/pay\//)
  assert.doesNotMatch(lifecycle,/https:\/\/www\.friendlypartyrental\.com\//)
  assert.match(orderRoute,/orderReceivedEmail/)
  assert.match(orderRoute,/Promise\.allSettled/)
  assert.match(admin,/automaticCancellationEmail/)
  assert.match(admin,/Promise\.allSettled/)
})

test('NYC admin displays checkout funnel and uses New York state defaults',()=>{
  assert.match(read('app/api/admin/orders/route.ts'),/checkoutStage: true/)
  assert.match(read('app/admin/orders/page.tsx'),/Status \/ Funnel/)
  assert.match(read('app/api/admin/orders/route.ts'),/eventState: body\.eventState \|\| 'NY'/)
  assert.doesNotMatch(read('app/api/admin/orders/route.ts'),/\|\| 'SC'/)
})
