const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
test('all Greenville tent-specific previews are photo-only',()=>{
  const card=fs.readFileSync('components/public/ItemCard.tsx','utf8')
  const cta=fs.readFileSync('components/public/DesignYourEventCTA.tsx','utf8')
  assert.match(card,/DesignYourEventCTA source="tent_item_card"/)
  assert.match(card,/label="View Tent Photo"/)
  assert.doesNotMatch(card,/See This Tent in a Layout/)
  assert.doesNotMatch(card,/open-design-your-event.*tent_item_card/)
  assert.match(cta,/if \(tent \|\| tentSlug\)/)
  assert.match(cta,/Rental tent photo/)
  assert.match(cta,/\/api\/item-image\//)
  const photoStart=cta.indexOf('if (tent || tentSlug)')
  const lockStart=cta.indexOf('if (!SC_RENTSKETCH_TENANT)')
  assert.ok(photoStart >= 0 && photoStart < lockStart,'specific tent photo must work even while SC RentSketch is locked')
})
