const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const read=p=>fs.readFileSync(p,'utf8')
test('Greenville service-area redesign stays truthful and delivery-only',()=>{
 const page=read('app/(public)/service-area/page.tsx')
 const dir=read('components/public/ServiceAreaDirectory.tsx')
 assert.match(page,/35 listed communities/)
 assert.match(page,/Delivery-only storefront/)
 assert.match(page,/No customer warehouse pickup/)
 assert.match(page,/not presented as a Greenville event/)
 assert.match(page,/SC_PRIORITY_AREAS/)
 assert.doesNotMatch(page,/330 Costello|Minoa|Syracuse|Central New York/)
 assert.match(dir,/SC_SERVICE_AREAS/)
 assert.match(dir,/Try Greer or 29650/)
 assert.match(dir,/864-610-5324/)
})
