import { nycPageMetadata, NYC_SITE_URL } from '@/lib/nycSeo'
import Link from 'next/link'
import type { Metadata } from 'next'
import { safeJsonLd } from '@/lib/jsonLd'
import { NYC_SERVICE_AREA_SUMMARY } from '@/lib/nycServiceAreas'
import { BUSINESS } from '@/lib/utils'
const BASE_URL=NYC_SITE_URL
export const metadata = nycPageMetadata("/chiavari-chair-rentals","Chiavari Chair Rentals in Riverdale, Bronx, NY","Browse Chiavari chairs for weddings and events in Riverdale and Downstate New York. Check quantities, event-date availability and delivery.")
export default function ChiavariChairRentalsPage(){
 const jsonLd={'@context':'https://schema.org','@type':'CollectionPage',name:'Chiavari Chair Rentals',description:'Chiavari chair rental options in Riverdale, Bronx, NY and Downstate New York.',url:`${BASE_URL}/chiavari-chair-rentals`}
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(jsonLd)}}/><div className="max-w-5xl mx-auto px-4 py-12">
 <h1 className="text-3xl font-bold text-dark mb-2">Chiavari Chair Rentals in Riverdale, Bronx, NY</h1><p className="text-body mb-8">Planning a wedding or upscale event in Downstate New York? Friendly Party Rental NYC supplies gold and white chiavari chairs for events in {NYC_SERVICE_AREA_SUMMARY}. Choose the finish that fits your event below, or call us to coordinate a large wedding order alongside tables, linens, and a tent.</p>
 <h2 className="font-bold text-dark mb-4 text-xl">Chiavari Chair Options</h2><div className="grid md:grid-cols-2 gap-6 mb-10">{[{name:'Gold Chiavari Chair',description:'A classic gold finish that pairs well with most wedding and gala color schemes.',slug:'gold-chiavari-chair'},{name:'White Chiavari Chair',description:'A bright white finish for garden weddings, all-white receptions, and daytime events.',slug:'white-chiavari-chair'}].map(item=><div key={item.slug} className="bg-white rounded-lg shadow-lg border-2 border-primary overflow-hidden p-4"><h3 className="text-xl font-bold text-dark mb-1">{item.name}</h3><p className="text-sm font-semibold text-secondary mb-2">Price and availability are shown for your event date.</p><p className="text-body text-sm mb-4">{item.description}</p><Link href={`/items/${item.slug}`} className="inline-block bg-primary text-white px-4 py-2 rounded font-bold">Check Availability &amp; Book</Link></div>)}</div>
 <h2 className="font-bold text-dark mb-4 text-xl">Planning a Wedding or Large Event?</h2><div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 mb-10 text-body">{[['/category/table-chair-rentals','All Tables & Chairs'],['/category/linen-rentals','Linens'],['/category/tent-rentals','Tent Rentals'],['/category/dance-floor-stage-rentals','Dance Floor & Stage'],['/category/event-lighting-rentals','Event Lighting'],['/weddings','Wedding Rentals']].map(([url,label])=><Link key={url} href={url} className="block bg-white border rounded-lg p-4 hover:shadow-md">{label}</Link>)}</div>
 <h2 className="font-bold text-dark mb-4 text-xl">Chiavari Chair Rental FAQ</h2><div className="mb-10 space-y-4"><div><p className="font-bold text-dark text-sm">What chiavari chair colors do you have available?</p><p className="text-body text-sm">Gold and white chiavari chairs are listed for NYC events. Check your event date to see what is available.</p></div><div><p className="font-bold text-dark text-sm">Do you deliver chiavari chairs to my town?</p><p className="text-body text-sm">We deliver to {NYC_SERVICE_AREA_SUMMARY}. Call {BUSINESS.phone} if your town isn&#39;t listed and we can review your location.</p></div><div><p className="font-bold text-dark text-sm">Can I order chiavari chairs along with tables, linens, and a tent for my wedding?</p><p className="text-body text-sm">Yes. Many couples order chiavari chairs alongside tables, linens, and a tent in one delivery. Call us and we&#39;ll help you plan the full order.</p></div></div>
 <h2 className="font-bold text-dark mb-4 text-xl">Why Riverdale Couples Choose Friendly Party Rental</h2><p className="text-body text-sm mb-2">Family-owned and operated, bringing Friendly Party Rental’s event-rental experience to Riverdale and Downstate New York. Clean, inspected equipment with delivery and collection from your event.</p>
 </div></>
}
