'use client'

import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'

interface Surface {
  id: string
    name: string
      isActive: boolean
        sortOrder: number
        }

        export default function SetupSurfacesPage() {
          const [surfaces, setSurfaces] = useState<Surface[]>([])
            const [loading, setLoading] = useState(true)
              const [newName, setNewName] = useState('')

                const load = async () => {
                    const res = await fetch('/api/admin/setup-surfaces')
                        const data = await res.json()
                            setSurfaces(data.surfaces || [])
                                setLoading(false)
                                  }

                                    useEffect(() => { load() }, [])

                                      const addSurface = async () => {
                                          if (!newName.trim()) return
                                              const res = await fetch('/api/admin/setup-surfaces', {
                                                    method: 'POST',
                                                          headers: { 'Content-Type': 'application/json' },
                                                                body: JSON.stringify({ name: newName, sortOrder: surfaces.length }),
                                                                    })
                                                                        if (res.ok) {
                                                                              toast.success('Surface added')
                                                                                    setNewName('')
                                                                                          load()
                                                                                              } else {
                                                                                                    toast.error('Failed to add surface')
                                                                                                        }
                                                                                                          }
                                                                                                          
                                                                                                            const toggleActive = async (s: Surface) => {
                                                                                                                const res = await fetch('/api/admin/setup-surfaces', {
                                                                                                                      method: 'PATCH',
                                                                                                                            headers: { 'Content-Type': 'application/json' },
                                                                                                                                  body: JSON.stringify({ id: s.id, isActive: !s.isActive }),
                                                                                                                                      })
                                                                                                                                          if (res.ok) {
                                                                                                                                                toast.success('Updated')
                                                                                                                                                      load()
                                                                                                                                                          }
                                                                                                                                                            }
                                                                                                                                                            
                                                                                                                                                              const removeSurface = async (id: string) => {
                                                                                                                                                                  if (!confirm('Remove this setup surface?')) return
                                                                                                                                                                      const res = await fetch(`/api/admin/setup-surfaces?id=${id}`, { method: 'DELETE' })
                                                                                                                                                                          if (res.ok) {
                                                                                                                                                                                toast.success('Removed')
                                                                                                                                                                                      load()
                                                                                                                                                                                          }
                                                                                                                                                                                            }
                                                                                                                                                                                            
                                                                                                                                                                                              if (loading) return <div className="p-4">Loading...</div>
                                                                                                                                                                                              
                                                                                                                                                                                                return (
                                                                                                                                                                                                    <div className="p-4">
                                                                                                                                                                                                          <h1 className="text-xl font-bold text-dark mb-2">Setup Surfaces</h1>
                                                                                                                                                                                                                <p className="text-sm text-gray-600 mb-6">Manage the list of ground surface types customers can select for delivery setup (e.g. Grass, Concrete, Indoor).</p>
                                                                                                                                                                                                                
                                                                                                                                                                                                                      <div className="bg-white rounded shadow p-4 mb-4">
                                                                                                                                                                                                                              <div className="flex gap-2">
                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                    type="text"
                                                                                                                                                                                                                                                                value={newName}
                                                                                                                                                                                                                                                                            onChange={(e) => setNewName(e.target.value)}
                                                                                                                                                                                                                                                                                        placeholder="New surface type name"
                                                                                                                                                                                                                                                                                                    className="border rounded px-3 py-2 text-sm flex-1"
                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                        <button onClick={addSurface} className="bg-admin-dark text-white px-4 py-2 rounded text-sm">Add</button>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                            <div className="bg-white rounded shadow divide-y">
                                                                                                                                                                                                                                                                                                                                                    {surfaces.map((s) => (
                                                                                                                                                                                                                                                                                                                                                              <div key={s.id} className="flex items-center justify-between px-4 py-3">
                                                                                                                                                                                                                                                                                                                                                                          <span className="text-sm">{s.name}</span>
                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                    <label className="flex items-center gap-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" checked={s.isActive} onChange={() => toggleActive(s)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                    Active
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => removeSurface(s.id)} className="text-red-600 text-sm">Delete</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {surfaces.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="px-4 py-3 text-sm text-gray-500">No setup surfaces yet.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
