'use client'

import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'

interface Reference {
  id: string
    name: string
      isActive: boolean
        sortOrder: number
        }

        export default function ReferencesPage() {
          const [references, setReferences] = useState<Reference[]>([])
            const [loading, setLoading] = useState(true)
              const [newName, setNewName] = useState('')

                const load = async () => {
                    const res = await fetch('/api/admin/references')
                        const data = await res.json()
                            setReferences(data.references || [])
                                setLoading(false)
                                  }

                                    useEffect(() => { load() }, [])

                                      const addReference = async () => {
                                          if (!newName.trim()) return
                                              const res = await fetch('/api/admin/references', {
                                                    method: 'POST',
                                                          headers: { 'Content-Type': 'application/json' },
                                                                body: JSON.stringify({ name: newName, sortOrder: references.length }),
                                                                    })
                                                                        if (res.ok) {
                                                                              toast.success('Reference added')
                                                                                    setNewName('')
                                                                                          load()
                                                                                              } else {
                                                                                                    toast.error('Failed to add reference')
                                                                                                        }
                                                                                                          }
                                                                                                          
                                                                                                            const toggleActive = async (ref: Reference) => {
                                                                                                                const res = await fetch('/api/admin/references', {
                                                                                                                      method: 'PATCH',
                                                                                                                            headers: { 'Content-Type': 'application/json' },
                                                                                                                                  body: JSON.stringify({ id: ref.id, isActive: !ref.isActive }),
                                                                                                                                      })
                                                                                                                                          if (res.ok) {
                                                                                                                                                toast.success('Updated')
                                                                                                                                                      load()
                                                                                                                                                          }
                                                                                                                                                            }
                                                                                                                                                            
                                                                                                                                                              const removeReference = async (id: string) => {
                                                                                                                                                                  if (!confirm('Remove this reference source?')) return
                                                                                                                                                                      const res = await fetch(`/api/admin/references?id=${id}`, { method: 'DELETE' })
                                                                                                                                                                          if (res.ok) {
                                                                                                                                                                                toast.success('Removed')
                                                                                                                                                                                      load()
                                                                                                                                                                                          }
                                                                                                                                                                                            }
                                                                                                                                                                                            
                                                                                                                                                                                              if (loading) return <div className="p-4">Loading...</div>
                                                                                                                                                                                              
                                                                                                                                                                                                return (
                                                                                                                                                                                                    <div className="p-4">
                                                                                                                                                                                                          <h1 className="text-xl font-bold text-dark mb-2">References</h1>
                                                                                                                                                                                                                <p className="text-sm text-gray-600 mb-6">Manage the list of referral sources shown when tracking how customers heard about us (e.g. Google, Facebook, Referral).</p>
                                                                                                                                                                                                                
                                                                                                                                                                                                                      <div className="bg-white rounded shadow p-4 mb-4">
                                                                                                                                                                                                                              <div className="flex gap-2">
                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                    type="text"
                                                                                                                                                                                                                                                                value={newName}
                                                                                                                                                                                                                                                                            onChange={(e) => setNewName(e.target.value)}
                                                                                                                                                                                                                                                                                        placeholder="New reference source name"
                                                                                                                                                                                                                                                                                                    className="border rounded px-3 py-2 text-sm flex-1"
                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                        <button onClick={addReference} className="bg-admin-dark text-white px-4 py-2 rounded text-sm">Add</button>
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                            <div className="bg-white rounded shadow divide-y">
                                                                                                                                                                                                                                                                                                                                                    {references.map((ref) => (
                                                                                                                                                                                                                                                                                                                                                              <div key={ref.id} className="flex items-center justify-between px-4 py-3">
                                                                                                                                                                                                                                                                                                                                                                          <span className="text-sm">{ref.name}</span>
                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                    <label className="flex items-center gap-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="checkbox" checked={ref.isActive} onChange={() => toggleActive(ref)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                    Active
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => removeReference(ref.id)} className="text-red-600 text-sm">Delete</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {references.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="px-4 py-3 text-sm text-gray-500">No reference sources yet.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
