'use client'

import { useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { driverNavigationUrl } from '@/lib/driverNavigation'

interface Stop { id:string; orderNumber:string; eventAddress?:string; eventCity?:string; eventState?:string; eventZip?:string; eventTimeSlot?:string; pickupTimeSlot?:string; customerName:string; customerPhone?:string; items:Array<{itemName:string;quantity:number}>; isDelivery:boolean; isPickup:boolean; canCompleteDelivery?:boolean; canCompletePickup?:boolean; canTakeActions?:boolean; deliveryUnassigned?:boolean; pickupUnassigned?:boolean; routeSequence:number|null; pickupRouteSequence:number|null; deliveryPhoto:string|null; pickupPhoto:string|null; deliveredAt:string|null; pickedUpAt:string|null; notes?:string; balanceDue:number; hasCardOnFile:boolean; contractSignedAt?:string|null; contractSignatureName?:string|null; contractUrl:string }
function toDateInputValue(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const SHARE_PREF_KEY='driverShareLocation'

export default function DriverRoutePage(){
 const router=useRouter(), [date,setDate]=useState(toDateInputValue(new Date())), [driverName,setDriverName]=useState(''), [stops,setStops]=useState<Stop[]>([]), [loading,setLoading]=useState(true), [error,setError]=useState(''), [sharingLocation,setSharingLocation]=useState(false), [locationStatus,setLocationStatus]=useState('')
 const watchIdRef=useRef<number|null>(null), fileInputRef=useRef<HTMLInputElement>(null), pendingPhotoRef=useRef<{orderId:string;action:'delivered'|'pickedUp'}|null>(null)
 const load=()=>{setLoading(true);fetch(`/api/driver/orders?date=${date}`).then(async r=>{if(r.status===401){router.push('/driver/login');return null}return r.json()}).then(d=>{if(d){setDriverName(d.driver?.name||'');setStops(d.stops||[])}}).catch(()=>setError('Could not load your route.')).finally(()=>setLoading(false))}
 useEffect(()=>{load()},[date])
 const sendLocation=(lat:number,lng:number)=>fetch('/api/driver/location',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lat,lng})}).catch(()=>{})
 const stopSharing=()=>{if(watchIdRef.current!==null&&navigator.geolocation){navigator.geolocation.clearWatch(watchIdRef.current);watchIdRef.current=null}setSharingLocation(false);setLocationStatus('');try{localStorage.setItem(SHARE_PREF_KEY,'off')}catch{}}
 const startSharing=()=>{if(!navigator.geolocation){setLocationStatus('Location is not supported on this device.');return}setSharingLocation(true);try{localStorage.setItem(SHARE_PREF_KEY,'on')}catch{};watchIdRef.current=navigator.geolocation.watchPosition(p=>{setLocationStatus('Sharing location ✓');sendLocation(p.coords.latitude,p.coords.longitude)},()=>setLocationStatus('Could not get your location.'),{enableHighAccuracy:true,maximumAge:15000,timeout:20000})}
 const markComplete=async(orderId:string,action:'delivered'|'pickedUp',photo?:string)=>{await fetch('/api/driver/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId,action,photo})});load()}
 const requestPhoto=(orderId:string,action:'delivered'|'pickedUp')=>{pendingPhotoRef.current={orderId,action};fileInputRef.current?.click()}
 const handlePhotoSelected=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0],pending=pendingPhotoRef.current;e.target.value='';if(!file||!pending)return;const reader=new FileReader();reader.onload=()=>{markComplete(pending.orderId,pending.action,reader.result as string);pendingPhotoRef.current=null};reader.readAsDataURL(file)}
 const logout=async()=>{stopSharing();await fetch('/api/driver/login',{method:'DELETE'});router.push('/driver/login')}
 const sorted=[...stops].sort((a,b)=>(a.routeSequence??a.pickupRouteSequence??999)-(b.routeSequence??b.pickupRouteSequence??999))
 return <div className="min-h-screen bg-gray-100 p-4">
  <input ref={fileInputRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={handlePhotoSelected}/>
  <div className="flex flex-wrap justify-between items-center gap-2 mb-4"><div><h1 className="text-xl font-bold">Hi, {driverName||'Driver'}</h1><p className="text-sm text-gray-500">{loading?'Loading...':`${sorted.length} stop(s) today`}</p></div><div className="flex gap-2"><a href="/driver/card-reader" className="text-sm px-3 py-2 rounded bg-green-700 text-white font-semibold">Take Card Payment</a><button onClick={logout} className="text-sm px-3 py-2 border rounded bg-white">Log Out</button></div></div>
  <div className="flex items-center gap-2 mb-4"><button onClick={sharingLocation?stopSharing:startSharing} className={`text-sm px-3 py-2 rounded font-semibold ${sharingLocation?'bg-gray-200':'bg-blue-600 text-white'}`}>{sharingLocation?'Stop Sharing Location':'Share My Location'}</button>{locationStatus&&<span className="text-xs text-gray-500">{locationStatus}</span>}</div>
  <input type="date" value={date} onChange={e=>setDate(e.target.value)} className="border rounded px-3 py-2 text-sm mb-4 bg-white"/>{error&&<p className="text-red-600 mb-3">{error}</p>}
  <div className="space-y-3">{sorted.map((s,idx)=><div key={s.id} className="bg-white rounded shadow p-4">
   <div><span className="text-xs font-semibold px-2 py-0.5 rounded bg-gray-200 mr-2">Stop #{idx+1}</span>{s.isDelivery&&<span className="text-xs font-semibold px-2 py-0.5 rounded bg-green-100 text-green-700 mr-1">Delivery</span>}{s.isPickup&&<span className="text-xs font-semibold px-2 py-0.5 rounded bg-red-100 text-red-700">Pickup</span>}<p className="font-medium mt-1">{s.orderNumber} · {s.customerName}</p><p className="text-sm text-gray-600">{s.eventAddress}{s.eventCity?`, ${s.eventCity}`:''} {s.eventState} {s.eventZip}</p>
   <a href={driverNavigationUrl(s)} target="_blank" rel="noopener noreferrer" className="text-sm text-blue-600 underline mr-3">Navigate</a>{s.customerPhone&&<a href={`tel:${s.customerPhone}`} className="text-sm text-blue-600 underline">{s.customerPhone}</a>}
   {s.eventTimeSlot&&<p className="text-xs text-gray-500 mt-1">Delivery time: {s.eventTimeSlot}</p>}{s.pickupTimeSlot&&<p className="text-xs text-gray-500">Pickup time: {s.pickupTimeSlot}</p>}<p className="text-xs text-gray-500 mt-1">{s.items.map(i=>`${i.itemName} x${i.quantity}`).join(', ')}</p>{s.notes&&<p className="text-xs text-amber-700 mt-1">Note: {s.notes}</p>}</div>
   <div className="mt-3 p-3 rounded-lg bg-gray-50 border"><div className="flex justify-between"><span className="font-semibold">Balance Due</span><span className={`font-bold ${s.balanceDue>0?'text-red-700':'text-green-700'}`}>${Number(s.balanceDue||0).toFixed(2)}</span></div>{s.balanceDue>0&&<p className="text-xs text-gray-500 mt-1">{s.hasCardOnFile?'Card on file available — full card number is never shown to drivers.':'No saved card on file.'}</p>}</div>
   <div className="mt-2 grid grid-cols-1 sm:grid-cols-2 gap-2">{s.contractSignedAt?<div className="px-3 py-3 rounded bg-green-50 border border-green-200 text-green-800 font-semibold text-sm">Contract Signed ✓{s.contractSignatureName?` — ${s.contractSignatureName}`:''}</div>:<a href={s.contractUrl} target="_blank" rel="noopener noreferrer" className="text-center px-3 py-3 rounded bg-blue-700 text-white font-semibold text-sm">Customer Sign Contract</a>}{s.balanceDue>0&&s.hasCardOnFile&&<div className="px-3 py-3 rounded border bg-amber-50 text-amber-900 text-sm font-semibold">Card on File · ${s.balanceDue.toFixed(2)} due<br/><span className="text-xs font-normal">Collection action pending protected payment approval</span></div>}</div>
   <div className="mt-3 pt-3 border-t flex flex-wrap gap-2">{s.isDelivery&&<button onClick={()=>markComplete(s.id,'delivered')} disabled={!!s.deliveredAt||s.canCompleteDelivery===false} className={`text-sm px-3 py-2 rounded font-semibold ${s.deliveredAt?'bg-green-100 text-green-700':'bg-green-700 text-white'}`}>{s.deliveredAt?'Delivered ✓':'Mark Delivered'}</button>}{s.isDelivery&&<button onClick={()=>requestPhoto(s.id,'delivered')} className="text-sm px-3 py-2 rounded font-semibold border bg-white">{s.deliveryPhoto?'Photo ✓ (retake)':'📷 Add Photo'}</button>}{s.isPickup&&<button onClick={()=>markComplete(s.id,'pickedUp')} disabled={!!s.pickedUpAt||s.canCompletePickup===false} className={`text-sm px-3 py-2 rounded font-semibold ${s.pickedUpAt?'bg-red-100 text-red-700':'bg-red-700 text-white'}`}>{s.pickedUpAt?'Picked Up ✓':'Mark Picked Up'}</button>}{s.isPickup&&<button onClick={()=>requestPhoto(s.id,'pickedUp')} className="text-sm px-3 py-2 rounded font-semibold border bg-white">{s.pickupPhoto?'Photo ✓ (retake)':'📷 Add Photo'}</button>}</div>
  </div>)}{!loading&&sorted.length===0&&<p className="text-gray-400">No stops for this date.</p>}</div>
 </div>
}
