import type {Metadata} from 'next'
import {Roboto} from 'next/font/google'
import {Toaster} from 'react-hot-toast'
import Script from 'next/script'
import {CartProvider} from '@/components/public/CartContext'
import {GOOGLE_TAG_ID,GOOGLE_TAG_BOOTSTRAP} from '@/lib/gtag'
import GoogleAnalyticsListener from '@/components/GoogleAnalyticsListener'
import VisitorTracker from '@/components/VisitorTracker'
import './globals.css'
import {safeJsonLd} from '@/lib/jsonLd'
import {SC_SERVICE_AREAS} from '@/lib/scServiceAreas'
const roboto=Roboto({weight:['300','400','500','700'],subsets:['latin'],display:'swap'})
const SITE_URL=(process.env.NEXT_PUBLIC_SITE_URL||process.env.SITE_URL||'https://fpr-nyc-production.up.railway.app').replace(/\/+$/,'')
const PUBLIC_INDEXABLE=process.env.PUBLIC_INDEXABLE==='true'
const SITE_DESCRIPTION='Friendly Party Rental NYC provides party and event rentals across Riverdale, the Bronx and Lower Westchester, including tents, tables, chairs, inflatables, weddings and event equipment.'
const LOCAL_BUSINESS_JSONLD={'@context':'https://schema.org','@type':'LocalBusiness','@id':SITE_URL+'/#business',name:'Friendly Party Rental NYC',legalName:'Friendly Party Rental L.L.C.',description:SITE_DESCRIPTION,image:SITE_URL+'/images/logo.png',telephone:'+1-315-884-1498',email:'customerservice@friendlypartyrental.com',url:SITE_URL,areaServed:SC_SERVICE_AREAS.map(a=>({'@type':'Place',name:a.name+', NY'})),openingHoursSpecification:[{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],opens:'09:00',closes:'18:00'}],hasOfferCatalog:{'@type':'OfferCatalog',name:'Party and event rentals in Riverdale, the Bronx and Lower Westchester',itemListElement:[{'@type':'OfferCatalog',name:'Tent Rentals',url:SITE_URL+'/category/tent-rentals'},{'@type':'OfferCatalog',name:'Table & Chair Rentals',url:SITE_URL+'/category/table-chair-rentals'},{'@type':'OfferCatalog',name:'Bounce House & Water Slide Rentals',url:SITE_URL+'/category/bounce-house-rentals'},{'@type':'OfferCatalog',name:'Wedding Rentals',url:SITE_URL+'/weddings'}]},priceRange:'$$'}
const WEBSITE_JSONLD={'@context':'https://schema.org','@type':'WebSite','@id':SITE_URL+'/#website',url:SITE_URL,name:'Friendly Party Rental NYC',description:SITE_DESCRIPTION,publisher:{'@id':SITE_URL+'/#business'}}
export const metadata:Metadata={metadataBase:new URL(SITE_URL),applicationName:'Friendly Party Rental NYC',manifest:'/site.webmanifest',title:{default:'Friendly Party Rental NYC | Party Rentals in Riverdale, NY',template:'%s | Friendly Party Rental NYC'},description:SITE_DESCRIPTION,keywords:['Friendly Party Rental NYC','party rentals Riverdale NY','tent rentals Bronx','bounce house rentals Westchester','table and chair rentals Lower Westchester','wedding rentals Riverdale NY'],robots:{index:PUBLIC_INDEXABLE,follow:PUBLIC_INDEXABLE},openGraph:{title:'Friendly Party Rental NYC | Party Rentals in Riverdale, NY',description:SITE_DESCRIPTION,siteName:'Friendly Party Rental NYC',locale:'en_US',type:'website',images:[{url:SITE_URL+'/images/logo.png',alt:'Friendly Party Rental NYC'}]},verification:{google:process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION}}
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="en"><head><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(LOCAL_BUSINESS_JSONLD)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(WEBSITE_JSONLD)}}/>{GOOGLE_TAG_ID&&<><Script id="ga4-init" strategy="beforeInteractive">{GOOGLE_TAG_BOOTSTRAP}</Script><Script src={`https://www.googletagmanager.com/gtag/js?id=${GOOGLE_TAG_ID}`} strategy="lazyOnload"/></>}</head><body className={roboto.className}><GoogleAnalyticsListener/><VisitorTracker/><CartProvider>{children}<Toaster position="top-center"/></CartProvider></body></html>}
