import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, CalendarDays, MapPin, MessageCircle, Phone, Truck } from 'lucide-react'
import DeliveryFeeChecker from '@/components/public/DeliveryFeeChecker'
import ServiceAreaDirectory from '@/components/public/ServiceAreaDirectory'
import {nycPageMetadata,nycBreadcrumbs,NYC_BUSINESS_ID,nycUrl} from '@/lib/nycSeo'
import {NYC_PRIORITY_AREAS,NYC_SERVICE_AREAS} from '@/lib/nycServiceAreas'
import {safeJsonLd} from '@/lib/jsonLd'
import styles from '@/components/public/ScServiceArea.module.css'
export const metadata=nycPageMetadata('/service-area','Party Rental Delivery Areas & Fee Checker — NYC / Lower Westchester','Check delivery fees and explore Friendly Party Rental NYC service areas across Riverdale, the Northwest Bronx and Lower Westchester.')
export default function ServiceAreaPage(){
 const schema={'@context':'https://schema.org','@type':'Service','@id':nycUrl('/service-area')+'#delivery',name:'Party rental delivery in Riverdale, the Northwest Bronx and Lower Westchester',serviceType:'Party and event equipment rental delivery',provider:{'@id':NYC_BUSINESS_ID},areaServed:NYC_SERVICE_AREAS.map(a=>({'@type':'Place',name:a.name+', NY'})),url:nycUrl('/service-area')}
 const priority=NYC_PRIORITY_AREAS.map(slug=>NYC_SERVICE_AREAS.find(area=>area.slug===slug)).filter(Boolean) as typeof NYC_SERVICE_AREAS
 return <div className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(nycBreadcrumbs([{name:'Home',path:'/'},{name:'NYC / Lower Westchester Delivery Areas',path:'/service-area'}]))}}/><DeliveryFeeChecker/>
 <section className={`${styles.wrap} ${styles.hero}`} aria-labelledby="service-area-heading"><div><p className={styles.eyebrow}>Riverdale, Northwest Bronx &amp; Lower Westchester</p><h1 id="service-area-heading">Your party rentals.<br/><span>Delivered to your event.</span></h1><p className={styles.heroCopy}>Friendly Party Rental NYC delivers tents, tables, chairs, inflatables, linens and event equipment throughout the current Riverdale, Northwest Bronx and Lower Westchester service area. Check the ZIP-zone delivery fee, then shop the rentals available for your event date.</p><div className={styles.heroActions}><Link href="/order-by-date" prefetch={false} className={styles.primaryLink}><CalendarDays size={18}/> Check your event date</Link><a href="#communities" className={styles.secondaryLink}>See all service areas <ArrowRight size={16}/></a></div></div><div className={styles.heroPhoto}><Image src="/images/event-planning/tent-patio-setup/image.png" alt="Friendly Party Rental event setup inspiration" fill sizes="(max-width: 767px) 100vw, 45vw"/><div className={styles.photoShade}/><div className={styles.photoCaption}><MapPin size={24}/><div><strong>NYC / Lower Westchester delivery</strong><span>Shared Friendly Party Rental event inspiration; site suitability is confirmed for each event.</span></div></div></div></section>
 <div className={styles.facts}><div className={`${styles.wrap} ${styles.factsInner}`}><div className={styles.fact}><Truck size={22}/><div><strong>Delivery-only storefront</strong><span>No customer warehouse pickup.</span></div></div><div className={styles.fact}><MapPin size={22}/><div><strong>{NYC_SERVICE_AREAS.length} listed service areas</strong><span>Riverdale plus selected Bronx and Lower Westchester communities.</span></div></div><div className={styles.fact}><MessageCircle size={22}/><div><strong>Check the ZIP-zone fee first</strong><span>Fixed fee by currently supported event ZIP.</span></div></div></div></div>
 <ServiceAreaDirectory/>
 <section className={styles.guidesBand}><div className={`${styles.wrap} ${styles.guides}`}><p className={styles.eyebrow}>Priority service areas</p><h2>Start with a local rental guide</h2><p className={styles.sectionIntro}>These are delivery-area guides for the NYC operation—not separate storefronts or warehouse locations.</p><div className={styles.guideGrid}>{priority.map(area=><Link key={area.slug} href={area.href} prefetch={false} className={styles.guideLink}>{area.name}, NY <ArrowRight size={15}/></Link>)}</div></div></section>
 <section className={`${styles.wrap} ${styles.contact}`}><div><h2>Don’t see your area?</h2><p>Share your event ZIP, date and equipment list and the NYC team can confirm whether the address is inside the current service area.</p></div><div className={styles.contactActions}><a href="tel:+13158841498" className={styles.secondaryLink}><Phone size={17}/> 315-884-1498</a><a href="sms:+13158841498" className={styles.secondaryLink}><MessageCircle size={17}/> Text us</a></div></section>
 <section className={`${styles.wrap} ${styles.bookingWrap}`}><div className={styles.booking}><div><p className={styles.goldEyebrow}>Ready to plan?</p><h2>Check your date, then build the order.</h2><p>Browse the same NYC catalog used at checkout. Delivery fees, tax, availability and optional services are confirmed before payment.</p></div><div className={styles.bookingActions}><Link href="/order-by-date" prefetch={false} className={styles.primaryLink}>Check my date <ArrowRight size={17}/></Link><Link href="/category/tent-rentals" prefetch={false} className={styles.secondaryLink}>Browse tents</Link><Link href="/category/table-chair-rentals" prefetch={false} className={styles.secondaryLink}>Tables &amp; chairs</Link></div></div></section>
 </div>
}
