export const DEFAULT_HOME_CONTENT:Record<string,string>={
 heroEyebrow:'Riverdale, the Bronx & Lower Westchester',
 heroHeading:'Party Rentals Made Easy in Riverdale',
 heroBody:'Tents, tables, chairs, inflatables, weddings and complete event setups delivered across Riverdale, the Bronx and Lower Westchester.',
 heroPrimaryLabel:'CHECK MY DATE',heroSecondaryLabel:'BROWSE RENTALS',
 heroTagline:'Family-Owned • Delivery & setup available',
 desktopPlanningHeading:'What are you planning?',
 desktopIntroHeading:'Party Rentals in Riverdale, the Bronx & Lower Westchester',
 desktopIntroBody:'Friendly Party Rental NYC provides tents, tables, chairs, inflatables, wedding rentals, event essentials, delivery, setup and pickup across Riverdale, selected Bronx neighborhoods and Lower Westchester.\n\nBrowse by category or start with your event date to see the rentals that fit your celebration.',
 desktopIntroButton:'Book Your Party Rentals Online',
 desktopBenefit1Heading:'Family-Owned',desktopBenefit1Body:'Friendly service for Riverdale, Bronx and Lower Westchester events.',
 desktopBenefit2Heading:'Clean, Event-Ready Equipment',desktopBenefit2Body:'Rental equipment is cleaned, inspected and prepared before delivery.',
 desktopBenefit3Heading:'Delivery, Setup & Pickup',desktopBenefit3Body:'Our team coordinates delivery and collection so you can focus on the event.',
 desktopPackagesHeading:'Wedding Rental Packages',shopCategoryHeading:'Shop by Category',viewAllRentalsButton:'VIEW ALL RENTALS',
 planningEventHeading:'Planning an Event?',planningEventBody:"Choose your event date to see what's available.",planningEventButton:'SELECT EVENT DATE',
 bounceEyebrow:'Kid Favorite',bounceHeading:'Bounce Houses & Water Slides',bounceBody:'Make your party unforgettable, browse our most fun rentals',bounceButton:'VIEW ALL BOUNCE HOUSES & WATER SLIDES',
 popularHeading:'Popular Rentals',packagesHeading:'Wedding & Event Packages',packagesBody:'All-in-one packages for weddings, ceremonies and celebrations of any size.',packagesButton:'VIEW ALL WEDDING PACKAGES',
 rentingEasyHeading:'Renting Is Easy',step1Label:'Pick Your Date',step2Label:'Choose Your Rentals',step3Label:'We Deliver',
 weddingBannerHeading:'Planning a Wedding or Large Event?',weddingBannerBody:'Explore our premium wedding rental packages.',weddingBannerButton:'VIEW WEDDING RENTALS',
 trust1Label:'Family Owned',trust2Label:'Clean, Quality Equipment',trust3Label:'Delivery & Setup Available',
 eventPlanningEyebrow:'A Complete Solution',eventPlanningHeading:'Full-Service Event Planning',eventPlanningBody:'We plan it and provide it, so there is no need to hire a separate event planner.',eventPlanningButton:'Learn About Event Planning',
 youtubeEyebrow:'As Seen In Action',youtubeHeading:'Watch Us on YouTube',
}
export const HOME_CONTENT_KEYS=Object.keys(DEFAULT_HOME_CONTENT)
