export const DEFAULT_HOME_CONTENT: Record<string, string> = {
  shopCategoryHeading: 'Shop by Category',
  viewAllRentalsButton: 'VIEW ALL RENTALS',
  planningEventHeading: 'Planning an Event?',
  planningEventBody: "Choose your event date to see what's available.",
  planningEventButton: 'SELECT EVENT DATE',
  bounceEyebrow: 'Kid Favorite',
  bounceHeading: 'Bounce Houses & Water Slides',
  bounceBody: 'Make your party unforgettable, browse our most fun rentals',
  bounceButton: 'VIEW ALL BOUNCE HOUSES & WATER SLIDES',
  popularHeading: 'Popular Rentals',
  packagesHeading: 'Wedding & Event Packages',
  packagesBody: 'All-in-one packages for weddings, ceremonies, and celebrations of any size.',
  packagesButton: 'VIEW ALL WEDDING PACKAGES',
  rentingEasyHeading: 'Renting Is Easy',
  step1Label: 'Pick Your Date',
  step2Label: 'Choose Your Rentals',
  step3Label: 'We Deliver',
  weddingBannerHeading: 'Planning a Wedding or Large Event?',
  weddingBannerBody: 'Explore our premium wedding rental packages.',
  weddingBannerButton: 'VIEW WEDDING RENTALS',
  trust1Label: 'Local & Family Owned',
  trust2Label: 'Clean, Quality Equipment',
  trust3Label: 'Delivery & Setup Available',
  eventPlanningEyebrow: 'A Complete Solution',
  eventPlanningHeading: 'Full-Service Event Planning',
  eventPlanningBody: 'We plan it and provide it, so there is no need to hire a separate event planner.',
  eventPlanningButton: 'Learn About Event Planning',
  youtubeEyebrow: 'As Seen In Action',
  youtubeHeading: 'Watch Us on YouTube',
}

export const HOME_CONTENT_KEYS = Object.keys(DEFAULT_HOME_CONTENT)
