-- Owner-approved NYC catalog (approved 2026-09-30), imported HIDDEN.
--
-- Prices: every published non-package Syracuse item captured on 2026-09-29
-- (data/nyc-premium-price-snapshot-20260930.json, 198 items) x 1.70, shown as clean
-- whole-dollar prices with the same rounding as scripts/apply-nyc-premium-prices.mjs.
-- Packages are excluded (quote only). No quantities are copied: the owner decided NYC
-- has its own stock, so every item is created with quantity 0 and displayToCustomer
-- false. An item goes live only when staff enter its NYC quantity and publish it.
--
-- Existing items are never changed (ON CONFLICT on the unique slug), the existing
-- category records are only referenced (never created or edited), and no customer,
-- order, payment or settings data is touched.
BEGIN;

DO $$
DECLARE
  items_before integer;
BEGIN
  SELECT COUNT(*) INTO items_before FROM "Item";
  RAISE NOTICE 'NYC catalog import: % items before import', items_before;
END $$;

INSERT INTO "Item" (
  "id", "name", "slug", "cost", "quantity", "displayToCustomer", "status", "categoryId", "sortOrder", "updatedAt"
)
SELECT
  'nyc-item-' || item.slug,
  item.name,
  item.slug,
  item.cost,
  0,
  false,
  'Available',
  category."id",
  item.sort_order,
  CURRENT_TIMESTAMP
FROM (VALUES
  ('10-12-oz-water-goblet', '10 1/2 oz. Water Goblet', 3, 'beverage-food-service', 1),
  ('10-58-dinner-plate', '10-5/8 Dinner Plate', 3, 'beverage-food-service', 2),
  ('10-gallon-insulated-beverage-dispenser', '10 Gallon Insulated Beverage Dispenser', 60, 'beverage-food-service', 3),
  ('10-inch-cake-plate', '10-Inch Cake Plate', 2, 'beverage-food-service', 4),
  ('10-x-10-ez-pop-up-canopy-tent', '10 x 10 EZ Pop Up Canopy Tent', 170, 'tent-rentals', 1),
  ('10-x-20-ez-pop-up-canopy-tent', '10 x 20 EZ Pop Up Canopy Tent', 300, 'tent-rentals', 2),
  ('100-lb-propane-tank', '100 lb. Propane Tank', 170, 'heater-fan-rentals', 1),
  ('108-round-polyester-tablecloth', '108 Round Polyester Tablecloth', 31, 'linen-rentals', 1),
  ('10x10-pop-up-sidewall', '10x10 Pop-Up Sidewall', 34, 'tent-rentals', 3),
  ('11-qt-round-soup-chafer', '11 Qt Round Soup Chafer', 68, 'beverage-food-service', 5),
  ('120-inch-round-polyester-tablecloth', '120 inch Round Polyester Tablecloth', 34, 'linen-rentals', 2),
  ('120-quart-hard-ice-chest-cooler', '120-Quart Hard Ice Chest Cooler', 43, 'beverage-food-service', 6),
  ('120-round-satin-tablecloth', '120 Round Satin Tablecloth', 38, 'linen-rentals', 3),
  ('120in-round-sequin-tablecloth-rose-gold', '120 Round Sequin Tablecloth', 38, 'linen-rentals', 4),
  ('132-round-polyester-tablecloth', '132 Round Polyester Tablecloth', 41, 'linen-rentals', 5),
  ('170k-btu-tent-heater', '170K BTU Tent Heater', 215, 'heater-fan-rentals', 2),
  ('18ft-purple-tropical-marble-double-bay-waterslide', '18ft Purple Tropical Marble Double Bay Waterslide', 680, 'bounce-house-rentals', 1),
  ('20-inch-fan', '20-Inch Fan', 34, 'heater-fan-rentals', 3),
  ('20-lb-propane-tank', '20 lb. Propane Tank', 43, 'heater-fan-rentals', 4),
  ('20-side-wall-tent', '20'' Side Wall Tent', 68, 'tent-rentals', 4),
  ('20-side-wall-with-windows', '20'' Side Wall with Windows', 85, 'tent-rentals', 5),
  ('20-x-20-frame-tent', '20 x 20 Frame Tent', 680, 'tent-rentals', 6),
  ('20-x-30-frame-tent', '20 x 30 Frame Tent', 810, 'tent-rentals', 7),
  ('20-x-40-frame-tent', '20 x 40 Frame Tent', 935, 'tent-rentals', 8),
  ('20x20-pole-tent', '20x20 Pole Tent', 425, 'tent-rentals', 9),
  ('20x30-pole-tent', '20x30 Pole Tent', 595, 'tent-rentals', 10),
  ('20x40-pole-tent', '20x40 Pole Tent', 765, 'tent-rentals', 11),
  ('22ft-tropical-lava-wave-marble-waterslide', '22ft Tropical Lava Wave Marble Waterslide', 850, 'bounce-house-rentals', 2),
  ('25-foot-movie-screen-with-projector', '25-Foot Movie Screen with Projector', 340, 'inflatable-movie-screen-rentals', 1),
  ('25-gallon-insulated-beverage-dispenser', '2.5 Gallon Insulated Beverage Dispenser', 43, 'beverage-food-service', 7),
  ('30-x-30-pole-tent', '30 x 30 Pole Tent', 980, 'tent-rentals', 12),
  ('30-x-45-pole-tent', '30 x 45 Pole Tent', 1190, 'tent-rentals', 13),
  ('30-x-60-pole-tent', '30 x 60 Pole Tent', 1445, 'tent-rentals', 14),
  ('30a-power-distribution-spider-box', '30A Power Distribution Spider Box', 42, 'generator-rentals', 1),
  ('30x40-classic-frame-tent', '30x40 Classic Frame Tent', 1190, 'tent-rentals', 15),
  ('32-gallon-trash-can', '32 Gallon Trash Can', 51, 'party-rental-accessories', 1),
  ('4-qt-round-chafer', '4 Qt Round Chafer', 51, 'beverage-food-service', 8),
  ('40-x-100-pole-tent', '40 x 100 Pole Tent', 3315, 'tent-rentals', 16),
  ('40-x-40-pole-tent', '40 x 40 Pole Tent', 2550, 'tent-rentals', 17),
  ('40-x-80-pole-tent', '40 x 80 Pole Tent', 3145, 'tent-rentals', 18),
  ('40x60-pole-tent', '40x60 Pole Tent', 2720, 'tent-rentals', 19),
  ('4375-watt-generator', '4375-Watt Generator', 215, 'generator-rentals', 2),
  ('45-oz-champagne-flute', '4.5 oz Champagne Flute', 3, 'beverage-food-service', 9),
  ('4ft-fill-and-chill-table', '4ft Fill and Chill Table', 68, 'table-chair-rentals', 1),
  ('5-oz-footed-rocks-glass', '5 oz Footed Rocks Glass', 3, 'beverage-food-service', 10),
  ('54x120-banquet-polyester-tablecloth', '54x120 Banquet Polyester Tablecloth', 27, 'linen-rentals', 6),
  ('55-oz-popcorn-kernel', '5.5 oz Popcorn Kernel', 9, 'concession-machine-rentals', 1),
  ('550w-bluetooth-speaker', '550W Bluetooth Speaker', 130, 'party-rental-accessories', 2),
  ('5ft-round-table', '5ft Round Table', 26, 'table-chair-rentals', 2),
  ('5ft-tumbling-timbers', '5ft Tumbling Timbers', 43, 'yard-game-rentals', 1),
  ('6-inch-bread-and-butter-plate', '6-Inch Bread and Butter Plate', 3, 'beverage-food-service', 11),
  ('60-oz-beverage-pitcher', '60 oz Beverage Pitcher', 17, 'beverage-food-service', 12),
  ('65-qt-round-top-chafer', '6.5 Qt Round Top Chafer', 43, 'beverage-food-service', 13),
  ('6ft-plastic-folding-table', '6ft Plastic Folding Table', 22, 'table-chair-rentals', 3),
  ('7-inch-salad-plate', '7-Inch Salad Plate', 3, 'beverage-food-service', 14),
  ('72-x-120-banquet-tablecloth', '72 x 120 Banquet Tablecloth', 31, 'linen-rentals', 7),
  ('725-oz-martini-glass', '7.25 oz Martini Glass', 3, 'beverage-food-service', 15),
  ('8-quart-full-size-chafer', '8-Quart Full-Size Chafer', 51, 'beverage-food-service', 16),
  ('80k-btu-tent-heater', '80K BTU Tent Heater', 170, 'heater-fan-rentals', 5),
  ('85-inch-rim-soup-bowl', '8.5-Inch Rim Soup Bowl', 4, 'beverage-food-service', 17),
  ('85-oz-wine-glass', '8.5 oz Wine Glass', 3, 'beverage-food-service', 18),
  ('8ft-banquet-table', '8ft Banquet Table', 24, 'table-chair-rentals', 4),
  ('8ft-x-31in-stage-skirt', '8ft x 31in Stage Skirt', 43, 'dance-floor-stage-rentals', 1),
  ('90-round-polyester-tablecloth', '90 Round Polyester Tablecloth', 29, 'linen-rentals', 8),
  ('90x132-banquet-polyester-tablecloth', '90x132 Banquet Polyester Tablecloth', 41, 'linen-rentals', 9),
  ('90x156-banquet-polyester-tablecloth', '90x156 Banquet Polyester Tablecloth', 44, 'linen-rentals', 10),
  ('9ft-table-runner', '9ft Table Runner', 7, 'linen-rentals', 11),
  ('audio-guest-book', 'Audio Guest Book', 340, 'weddings', 1),
  ('battery-operated-crystal-chandelier', 'Battery-Operated Crystal Chandelier', 170, 'event-lighting-rentals', 1),
  ('bistro-lighting-20x20', 'Bistro Lighting (20x20)', 215, 'event-lighting-rentals', 2),
  ('black-spandex-6ft-table-linen', 'Spandex 6ft Table Linen', 31, 'linen-rentals', 12),
  ('black-spandex-8ft-table-linen', 'Black Spandex 8ft Table Linen', 34, 'linen-rentals', 13),
  ('bus-bin', 'Bus Bin', 9, 'beverage-food-service', 19),
  ('cake-fork', 'Cake Fork', 3, 'beverage-food-service', 20),
  ('chess-set', 'Chess Set', 43, 'yard-game-rentals', 2),
  ('chocolate-fountain', 'Chocolate Fountain', 130, 'beverage-food-service', 21),
  ('cocktail-table', 'Cocktail Table', 20, 'table-chair-rentals', 5),
  ('cocktail-table-cover-white', 'Cocktail Table Cover', 20, 'linen-rentals', 14),
  ('coffee-urn-percolator', 'Coffee Urn / Percolator', 60, 'beverage-food-service', 22),
  ('cornhole', 'Cornhole', 68, 'yard-game-rentals', 3),
  ('cotton-candy-floss-sugar-blue-raspberry', 'Cotton Candy Floss Sugar - Blue Raspberry', 17, 'concession-machine-rentals', 2),
  ('cotton-candy-floss-sugar-grape', 'Cotton Candy Floss Sugar - Grape', 17, 'concession-machine-rentals', 3),
  ('cotton-candy-floss-sugar-lemon', 'Cotton Candy Floss Sugar - Lemon', 17, 'concession-machine-rentals', 4),
  ('cotton-candy-floss-sugar-pink', 'Cotton Candy Floss Sugar - Pink', 17, 'concession-machine-rentals', 5),
  ('cotton-candy-machinefloss-maker', 'Cotton Candy Machine/Floss Maker', 170, 'concession-machine-rentals', 6),
  ('crayon-bounce-house', 'Rainbow Castle Bounce House', 340, 'bounce-house-rentals', 3),
  ('cross-back-farmhouse-chair', 'Cross-Back Farmhouse Chair', 24, 'weddings', 2),
  ('crowd-control-stanchion', 'Crowd Control Stanchion', 26, 'party-rental-accessories', 3),
  ('custom-lighting-300ft', 'Custom Lighting - 300ft', 340, 'event-lighting-rentals', 3),
  ('dance-floor-3x3-section', 'Dance Floor 3x3 Section', 60, 'dance-floor-stage-rentals', 2),
  ('dinner-fork', 'Dinner Fork', 3, 'beverage-food-service', 23),
  ('dinner-knife', 'Dinner Knife', 3, 'beverage-food-service', 24),
  ('extra-movie-night-speaker', 'Extra Movie Night Speaker', 94, 'inflatable-movie-screen-rentals', 2),
  ('fire-red-marble-inflatable-water-slide', 'Fire Red Marble Inflatable Water Slide', 510, 'bounce-house-rentals', 4),
  ('fire-truck-water-slide-bounce-house', 'Fire Truck Water Slide Bounce House', 595, 'bounce-house-rentals', 5),
  ('foam-party-machine', 'Foam Party Machine', 470, 'foam-party-machine-rentals', 1),
  ('freezer-chest', 'Freezer Chest', 85, 'beverage-food-service', 25),
  ('giant-uno-cards', 'Giant Uno Cards', 34, 'yard-game-rentals', 4),
  ('glass-beaded-charger-plate', 'Glass Beaded Charger Plate', 4, 'weddings', 3),
  ('glass-carafe', 'Glass Carafe', 7, 'beverage-food-service', 26),
  ('glass-coffee-mug', 'Glass Coffee Mug', 4, 'beverage-food-service', 27),
  ('glass-water-pitcher-64-oz', 'Glass Water Pitcher (64 oz)', 17, 'beverage-food-service', 28),
  ('gold-5-arm-candelabra', 'Gold 5-Arm Candelabra', 34, 'weddings', 4),
  ('gold-beaded-charger-plate', 'Gold Beaded Charger Plate', 4, 'weddings', 5),
  ('gold-card-box', 'Gold Card Box', 26, 'weddings', 6),
  ('gold-chiavari-chair', 'Gold Chiavari Chair', 20, 'table-chair-rentals', 6),
  ('gold-mirror-welcome-sign', 'Gold Mirror Welcome Sign', 60, 'weddings', 7),
  ('gold-pedestal-cake-stand-14in', 'Gold Pedestal Cake Stand (14in)', 26, 'weddings', 8),
  ('gold-welcome-sign-easel', 'Gold Welcome Sign Easel', 43, 'weddings', 9),
  ('greenery-and-floral-wall-8x8', 'Greenery and Floral Wall (8x8)', 255, 'weddings', 10),
  ('handwashing-station', 'Handwashing Station', 340, 'restroom-rentals', 1),
  ('hexagon-wedding-arch', 'Hexagon Wedding Arch', 130, 'weddings', 11),
  ('hot-dog-bun-warmer', 'Hot Dog Bun Warmer', 51, 'concession-machine-rentals', 7),
  ('hot-dog-roller-grill', 'Hot Dog Roller Grill', 160, 'concession-machine-rentals', 8),
  ('inflatable-basketball-game', 'Inflatable Basketball Game', 170, 'bounce-house-rentals', 6),
  ('keg-coolertub', 'Keg Cooler/Tub', 34, 'beverage-food-service', 29),
  ('king-throne-chair', 'King Throne Chair', 204, 'table-chair-rentals', 7),
  ('ladderball', 'Ladderball', 68, 'yard-game-rentals', 5),
  ('large-connect-four', 'Large Connect Four', 51, 'yard-game-rentals', 6),
  ('large-family-style-serving-bowl', 'Plastic Round Catering / Serving Bowl', 4, 'beverage-food-service', 30),
  ('leg-drape', 'Leg Drape', 43, 'tent-rentals', 20),
  ('madison-arbor', 'Madison Arbor', 130, 'weddings', 12),
  ('mahogany-chiavari-chair', 'Mahogany Chiavari Chair', 20, 'table-chair-rentals', 8),
  ('matching-napkins', 'Matching Napkins', 4, 'linen-rentals', 15),
  ('movie-night-laptop-rental', 'Movie Night Laptop Rental', 130, 'inflatable-movie-screen-rentals', 3),
  ('nacho-cheese-warmer', 'Nacho Cheese Warmer', 68, 'concession-machine-rentals', 9),
  ('patriotic-red-white-and-blue-bounce-house', 'Patriotic Red, White and Blue Bounce House', 425, 'bounce-house-rentals', 7),
  ('photobooth-3-hour-with-attendant', 'Photobooth (3-Hour) With Attendant', 930, 'photobooth-rentals', 1),
  ('photobooth-4-hour-no-attendant', 'Photobooth (4-Hour) No Attendant', 640, 'photobooth-rentals', 2),
  ('photobooth-4-hour-with-attendant', 'Photobooth (4-Hour) With Attendant', 1100, 'photobooth-rentals', 3),
  ('photobooth-4x6-print-upgrade', 'Photobooth 4x6 Print Upgrade', 170, 'photobooth-rentals', 4),
  ('photobooth-6-hour-no-attendant', 'Photobooth (6-Hour) No Attendant', 810, 'photobooth-rentals', 5),
  ('photobooth-6-hour-with-attendant', 'Photobooth (6-Hour) With Attendant', 1350, 'photobooth-rentals', 6),
  ('photobooth-8-hour-no-attendant', 'Photobooth (8-Hour) No Attendant', 980, 'photobooth-rentals', 7),
  ('photobooth-8-hour-with-attendant', 'Photobooth (8-Hour) With Attendant', 1625, 'photobooth-rentals', 8),
  ('photobooth-custom-backdrop-upgrade', 'Photobooth Custom Backdrop Upgrade', 145, 'photobooth-rentals', 9),
  ('photobooth-extra-hour-attended', 'Photobooth Extra Hour (Attended)', 170, 'photobooth-rentals', 10),
  ('piecake-server', 'Pie/Cake Server', 4, 'beverage-food-service', 31),
  ('pilsner-beer-glass', 'Pilsner Beer Glass', 4, 'beverage-food-service', 32),
  ('pink-inflatable-bounce-house', 'Pink Inflatable Bounce House', 340, 'bounce-house-rentals', 8),
  ('pirate-ship-slide-combo-bounce-house', 'Pirate Ship Slide Combo Bounce House', 680, 'bounce-house-rentals', 9),
  ('plastic-linen-clips', 'Plastic Linen Clips (12 Pack)', 7, 'linen-rentals', 16),
  ('podium-and-microphone', 'Podium and Microphone', 170, 'party-rental-accessories', 4),
  ('pong-game', 'Pong Game', 43, 'yard-game-rentals', 7),
  ('popcorn-machine', 'Popcorn Machine', 130, 'concession-machine-rentals', 10),
  ('pretzel-display-warmer', 'Pretzel Display Warmer', 130, 'concession-machine-rentals', 11),
  ('propane-heater', 'Propane Heater', 136, 'heater-fan-rentals', 6),
  ('queen-tiffany-throne-chair', 'Queen Tiffany Throne Chair', 215, 'table-chair-rentals', 9),
  ('red-carpet', 'Red Carpet', 130, 'party-rental-accessories', 5),
  ('roll-top-8-qt-chafer', 'Roll-Top 8 Qt Chafer', 77, 'beverage-food-service', 33),
  ('round-gold-metal-display-dish', 'Round Gold Metal Display Dish', 17, 'weddings', 13),
  ('round-wedding-arch-7ft', 'Round Wedding Arch (7ft)', 130, 'weddings', 14),
  ('rustic-lantern-table-centerpiece', 'Rustic Lantern Table Centerpiece', 43, 'table-chair-rentals', 10),
  ('salad-fork', 'Salad Fork', 3, 'beverage-food-service', 34),
  ('salt-and-pepper-shaker-set', 'Salt and Pepper Shaker Set', 6, 'beverage-food-service', 35),
  ('sequin-backdrop-panel-8x8', 'Sequin Backdrop Panel (8x8)', 170, 'weddings', 15),
  ('serving-spoon', 'Serving Spoon', 6, 'beverage-food-service', 36),
  ('serving-tongs', 'Serving Tongs', 4, 'beverage-food-service', 37),
  ('sheet-pan', 'Sheet Pan', 13, 'beverage-food-service', 38),
  ('snow-cone-machine', 'Snow Cone Machine', 94, 'concession-machine-rentals', 12),
  ('snow-cone-syrup-blue-raspberry', 'Snow Cone Syrup - Blue Raspberry', 14, 'concession-machine-rentals', 13),
  ('snow-cone-syrup-cherry', 'Snow Cone Syrup - Cherry', 14, 'concession-machine-rentals', 14),
  ('snow-cone-syrup-orange', 'Snow Cone Syrup - Orange', 14, 'concession-machine-rentals', 15),
  ('snow-cone-syrup-pina-colada', 'Snow Cone Syrup - Pina Colada', 14, 'concession-machine-rentals', 16),
  ('spandex-chair-cover', 'Spandex Chair Cover', 4, 'linen-rentals', 17),
  ('stage-ramp', 'Stage Ramp', 85, 'dance-floor-stage-rentals', 3),
  ('stage-section', 'Stage Section', 215, 'dance-floor-stage-rentals', 4),
  ('stage-stair', 'Stage Stair', 94, 'dance-floor-stage-rentals', 5),
  ('standard-portable-restroom', 'Standard Portable Restroom', 510, 'restroom-rentals', 2),
  ('sterno-fuel-cans-pack-of-2', 'Sterno Fuel Cans (Pack of 2)', 9, 'beverage-food-service', 39),
  ('sugar-and-creamer-set', 'Sugar and Creamer Set', 9, 'beverage-food-service', 40),
  ('sweetheart-table-60in-half-round', 'Sweetheart Table (60in Half-Round)', 60, 'weddings', 16),
  ('table-number-stands', 'Table Number Stands', 4, 'beverage-food-service', 41),
  ('tablespoon-soup-spoon', 'Tablespoon / Soup Spoon', 3, 'beverage-food-service', 42),
  ('tall-highball-glass', 'Tall Highball Glass', 3, 'beverage-food-service', 43),
  ('teaspoon', 'Teaspoon', 3, 'beverage-food-service', 44),
  ('tent-lighting-20x20', 'Tent Lighting (20x20)', 170, 'event-lighting-rentals', 4),
  ('tent-lighting-20x30', 'Tent Lighting - 20x30', 215, 'event-lighting-rentals', 5),
  ('tent-lighting-20x40', 'Tent Lighting (20x40)', 255, 'event-lighting-rentals', 6),
  ('tent-lighting-30x30', 'Tent Lighting - 30x30', 215, 'event-lighting-rentals', 7),
  ('tent-lighting-30x45', 'Tent Lighting - 30x45', 300, 'event-lighting-rentals', 8),
  ('tent-lighting-30x60', 'Tent Lighting - 30x60', 340, 'event-lighting-rentals', 9),
  ('tent-lighting-40x100', 'Tent Lighting - 40x100', 595, 'event-lighting-rentals', 10),
  ('tent-lighting-40x40', 'Tent Lighting - 40x40', 385, 'event-lighting-rentals', 11),
  ('tent-lighting-40x60', 'Tent Lighting - 40x60', 425, 'event-lighting-rentals', 12),
  ('tent-lighting-40x80', 'Tent Lighting - 40x80', 510, 'event-lighting-rentals', 13),
  ('tent-misting-10x10-pop-up-tent', 'Tent Misting 10x10 Pop Up Tent', 255, 'tent-rentals', 21),
  ('tidal-wave-inflatable-water-slide', 'Tidal Wave Inflatable Water Slide', 425, 'bounce-house-rentals', 10),
  ('tiered-cake-display-3-level-gold', 'Tiered Cake Display - 3-Level Gold', 43, 'weddings', 17),
  ('water-barrel-cover', 'Water Barrel Cover', 34, 'tent-rentals', 22),
  ('wedding-white-bounce-house', 'Wedding White Bounce House', 425, 'bounce-house-rentals', 11),
  ('white-aisle-runner-100ft', 'White Aisle Runner (100ft)', 170, 'weddings', 18),
  ('white-chiavari-chair', 'White Chiavari Chair', 20, 'table-chair-rentals', 11),
  ('white-plastic-folding-chair', 'White Plastic Folding Chair', 5, 'table-chair-rentals', 12),
  ('white-resin-folding-chair', 'White Resin Folding Chair', 9, 'table-chair-rentals', 13),
  ('white-table-linen-round-60', 'White Table Linen Round 60"', 27, 'linen-rentals', 18),
  ('wine-champagne-bucket', 'Wine / Champagne Bucket', 26, 'beverage-food-service', 45),
  ('wireless-led-uplight', 'Wireless LED Uplight', 43, 'event-lighting-rentals', 14)
) AS item(slug, name, cost, category_slug, sort_order)
JOIN "Category" category ON category."slug" = item.category_slug
ON CONFLICT ("slug") DO NOTHING;

-- Aggregate counts only (no personal data or secrets) in the deployment log.
DO $$
DECLARE
  item_count integer;
  hidden_count integer;
  published_count integer;
  unpriced_count integer;
BEGIN
  SELECT COUNT(*), COUNT(*) FILTER (WHERE NOT "displayToCustomer"), COUNT(*) FILTER (WHERE "displayToCustomer"), COUNT(*) FILTER (WHERE "cost" <= 0)
    INTO item_count, hidden_count, published_count, unpriced_count FROM "Item";
  RAISE NOTICE 'NYC catalog import: items %, hidden %, published %, priced at or below $0 %',
    item_count, hidden_count, published_count, unpriced_count;
END $$;

COMMIT;
