'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
type Draft = { id: string; name: string; status: string; scheduledAt?: string | null; segment?: string | null; sendError?: string | null }
export default function MarketingReviewQueue() {
  const [drafts, setDrafts] = useState<Draft[] | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState('')
  async function load() { try { const r = await fetch('/api/admin/email-templates-marketing'); const j = await r.json(); if (!r.ok) throw new Error(j.error || 'Could not load review queue'); setDrafts(j.items.filter((d: Draft) => ['scheduled','scheduled_review','review_ready','failed','partial'].includes(d.status)).sort((a: Draft,b: Draft) => new Date(a.scheduledAt || 0).getTime() - new Date(b.scheduledAt || 0).getTime())); setError('') } catch(e) { setError(String(e)) } }
  useEffect(() => { void load() }, [])
  async function cancel(id: string) { setBusy(id); try { const r = await fetch('/api/admin/email-templates-marketing',{ method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:'draft',scheduledAt:null}) }); if(!r.ok) throw new Error('Could not cancel review schedule'); await load() } catch(e) {setError(String(e))} finally {setBusy('')} }
  return <section className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-bold">Saved schedule & approval queue</h2><button className="text-sm underline" onClick={load}>Refresh</button></div><p className="mt-2 text-sm text-gray-500">Review dates use your browser's local time. Campaigns remain unsent until you explicitly launch them.</p>{error && <p role="alert" className="mt-3 text-red-700">{error}</p>}{!drafts && !error ? <p className="mt-3">Loading schedule…</p> : <div className="mt-4 space-y-3">{drafts?.map(d => <div key={d.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3"><div><strong className="text-sm">{d.name}</strong><p className="text-xs text-gray-500">{d.status.replace(/_/g,' ')} · {d.scheduledAt ? new Date(d.scheduledAt).toLocaleString() : 'No review time'} · {d.segment || 'all'}</p>{d.sendError && <p className="mt-1 text-xs text-red-700">{d.sendError}</p>}</div><div className="flex gap-4 text-sm"><Link className="text-blue-700 underline" href={`/admin/marketing/campaigns/builder?draft=${d.id}`}>Review campaign</Link>{['scheduled','scheduled_review'].includes(d.status) && <button disabled={!!busy} className="underline" onClick={() => cancel(d.id)}>Cancel schedule</button>}</div></div>)}{drafts?.length === 0 && <p className="text-sm text-gray-500">No scheduled reviews or campaigns requiring attention.</p>}</div>}<Link href="/admin/marketing/campaigns" className="mt-4 inline-block text-sm text-blue-700 underline">Prepare a campaign →</Link></section>
}
