import fs from 'node:fs';import path from 'node:path';
const root=process.cwd(),cfg=JSON.parse(fs.readFileSync(path.join(root,'config/site.json'),'utf8')),out=path.join(root,'dist');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
for(const file of ['styles.css','site.js'])fs.copyFileSync(path.join(root,'public',file),path.join(out,file));
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const nav=`<div class="topbar"><div class="wrap"><span>Riverdale + Lower Westchester market test</span><span><a href="${cfg.phoneHref}">${esc(cfg.phoneDisplay)}</a> • Downstate New York</span></div></div><nav class="nav"><div class="wrap navin"><a class="brand" href="/"><span class="mark">F</span><span>Friendly Party Rental <small>Downstate</small></span></a><div class="links"><a href="/#services">Rentals</a><a href="/#areas">Service Area</a><a href="/#quote">Quote</a></div><a class="btn" href="#quote">${esc(cfg.quoteCta)}</a></div></nav>`;
const footer=`<footer class="footer"><div class="wrap footerin"><div><strong>Friendly Party Rental — Downstate New York</strong><br>Serving Riverdale, selected Bronx neighborhoods & Lower Westchester.</div><div><a href="${esc(cfg.phoneHref)}">${esc(cfg.phoneDisplay)}</a><br><a href="${esc(cfg.emailHref)}">${esc(cfg.emailDisplay)}</a></div></div></footer>`;
function form(source='homepage'){return `<form class="form" data-quote-form><input type="hidden" name="source" value="${esc(source)}"><div class="row"><div class="field"><label>Name</label><input name="name" autocomplete="name" required></div><div class="field"><label>Email</label><input name="email" type="email" autocomplete="email" required></div></div><div class="row"><div class="field"><label>Phone</label><input name="phone" autocomplete="tel"></div><div class="field"><label>Event date</label><input name="eventDate" type="date" required></div></div><div class="row"><div class="field"><label>City / neighborhood</label><input name="city" required></div><div class="field"><label>Estimated guests</label><input name="guests" inputmode="numeric"></div></div><div class="field"><label>What do you need?</label><textarea name="items" rows="5" placeholder="Tent size, tables, chairs, bounce house, water slide, lighting, dance floor…" required></textarea></div><div class="notice">${esc(cfg.minimumOrder.display)}</div><button class="btn" type="submit">Request My Quote</button><div class="status" data-status></div><p class="fine">Submitting a request does not reserve equipment. Availability and site suitability must be confirmed.</p></form>`}
function page({title,description,body,canonical=''}){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#0d5b3b">${canonical?`<link rel="canonical" href="${esc(canonical)}">`:''}<link rel="stylesheet" href="/styles.css"></head><body>${nav}${body}${footer}<script src="/site.js" defer></script></body></html>`}
const serviceCards=cfg.services.map((s,i)=>`<a class="card" href="/rentals/${s.slug}/"><span class="num">0${i+1}</span><h3>${esc(s.name)}</h3><p>${esc(s.blurb)}</p><span class="card-link">View rentals →</span></a>`).join('');
const areaCards=cfg.areas.sort((a,b)=>a.priority-b.priority).map(a=>`<a class="card" href="/${a.slug}/"><span class="num">SERVICE AREA</span><h3>${esc(a.name)}</h3><p>${esc(a.summary)}</p></a>`).join('');
const homeBody=`<main><section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">● NOW BOOKING DOWNSTATE NEW YORK</span><h1>${esc(cfg.headline)}</h1><p class="lead">${esc(cfg.subheadline)}</p><div class="actions"><a class="btn" href="#quote">Check My Date</a><a class="btn alt" href="#services">Browse Rentals</a></div><div class="facts"><span class="fact">Family-owned</span><span class="fact">10+ years in event rentals</span><span class="fact">Professional setup</span></div></div><div class="hero-card"><div class="tent-art"><div class="tent"></div></div><h3>Backyard parties, weddings, schools, and celebrations — handled.</h3><p>Site-appropriate tents, seating, inflatables, lighting, and complete event setups.</p></div></div></section><section class="section" id="services"><div class="wrap"><h2>Everything you need for a polished event.</h2><p class="section-intro">From backyard birthdays to weddings and school events, we bring the equipment, delivery, and setup together in one place.</p><div class="grid">${serviceCards}</div></div></section><section class="section"><div class="wrap"><div class="band"><div><h2>Riverdale, the Bronx, and Lower Westchester.</h2><p>A focused service area lets our crew deliver dependable setup and pickup without spreading routes too thin.</p><div class="pills"><span class="pill">Riverdale</span><span class="pill">Fieldston</span><span class="pill">Kingsbridge</span><span class="pill">Yonkers</span><span class="pill">Mount Vernon</span><span class="pill">New Rochelle</span></div></div><div><a class="btn" href="#quote">Request a Downstate Quote</a></div></div></div></section><section class="section" id="areas"><div class="wrap"><h2>Service areas.</h2><p class="section-intro">We are booking events across Riverdale and nearby Bronx and Lower Westchester communities. Send your address and date to confirm delivery.</p><div class="grid">${areaCards}</div></div></section><section class="section" id="quote"><div class="wrap quote"><div><span class="eyebrow">GET A FAST QUOTE</span><h2>Tell us the date, location, and equipment.</h2><p class="section-intro">We will confirm availability, delivery logistics, site requirements, and the right setup for your event.</p><div class="card"><span class="num">BEFORE WE QUOTE</span><h3>We confirm the site, route, and setup.</h3><p>For tents and inflatables, surface type, usable space, access, anchoring, power, and pickup timing can affect the final setup and price.</p></div></div>${form()}</div></section></main>`;
fs.writeFileSync(path.join(out,'index.html'),page({title:'Party Rentals Riverdale & Lower Westchester | Friendly Party Rental',description:'Tent rentals, tables, chairs, inflatables, lighting and event rentals serving Riverdale, the Bronx and Lower Westchester.',body:homeBody}));
for(const a of cfg.areas){const body=`<main><section class="local-hero"><div class="wrap"><div class="crumb"><a href="/">Home</a> / ${esc(a.name)}</div><span class="eyebrow">FRIENDLY PARTY RENTAL • DOWNSTATE</span><h1>Party rentals in ${esc(a.name)}</h1><p class="lead">${esc(a.summary)}</p><div class="facts"><span class="fact">Tents</span><span class="fact">Tables & chairs</span><span class="fact">Inflatables</span><span class="fact">Event extras</span></div></div></section><section class="section"><div class="wrap"><h2>What we can bring to ${esc(a.name)}.</h2><div class="grid">${serviceCards}</div></div></section><section class="section" id="quote"><div class="wrap quote"><div><h2>Check your ${esc(a.name)} event date.</h2><p class="section-intro">Send the event address area, date, guest count, and rental list. We confirm availability, delivery logistics, site suitability, and final pricing before booking.</p><div class="notice">For pole tents and inflatables, the property must have suitable space and anchoring conditions. Frame-style or weighted options may be better for paved sites.</div></div>${form(a.slug)}</div></section></main>`;fs.mkdirSync(path.join(out,a.slug),{recursive:true});fs.writeFileSync(path.join(out,a.slug,'index.html'),page({title:`Party Rentals ${a.name}, ${a.region} | Friendly Party Rental`,description:`Friendly Party Rental serving ${a.name}: tents, tables, chairs, inflatables, lighting, dance floors and event rentals.`,body}));}
for(const s of cfg.services){const body=`<main><section class="local-hero"><div class="wrap"><div class="crumb"><a href="/">Home</a> / Rentals / ${esc(s.name)}</div><span class="eyebrow">RIVERDALE + LOWER WESTCHESTER</span><h1>${esc(s.name)} for Downstate events</h1><p class="lead">${esc(s.blurb)}</p></div></section><section class="section" id="quote"><div class="wrap quote"><div><h2>Check availability.</h2><p class="section-intro">Tell us where the event is and what you need. We will confirm the correct equipment, site conditions, delivery plan, and pricing.</p></div>${form(s.slug)}</div></section></main>`;fs.mkdirSync(path.join(out,'rentals',s.slug),{recursive:true});fs.writeFileSync(path.join(out,'rentals',s.slug,'index.html'),page({title:`${s.name} Riverdale & Lower Westchester | Friendly Party Rental`,description:`${s.blurb} Serving selected Downstate New York areas.`,body}));}
const robots=`User-agent: *\nAllow: /\n${cfg.publicBaseUrl?`Sitemap: ${cfg.publicBaseUrl.replace(/\/$/,'')}/sitemap.xml\n`:''}`;fs.writeFileSync(path.join(out,'robots.txt'),robots);
const urls=['/',...cfg.areas.map(a=>`/${a.slug}/`),...cfg.services.map(s=>`/rentals/${s.slug}/`)];
const base=(cfg.publicBaseUrl||'https://example.com').replace(/\/$/,'');fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${base}${u}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync(path.join(out,'404.html'),page({title:'Page not found | Friendly Party Rental',description:'Page not found',body:'<main><section class="section"><div class="wrap"><h1>That page is not here.</h1><p class="lead">Return to the Friendly Party Rental Downstate homepage.</p><a class="btn" href="/">Go Home</a></div></section></main>'}));
console.log(`Built ${urls.length} indexed pages into dist/`);
