-- Add additional item detail fields for richer item management (ERS-style)
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "specialDisplayName" TEXT;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "sku" TEXT;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "setupArea" TEXT;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "actualSize" TEXT;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "attendants" INTEGER;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "ageGroup" TEXT;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "additionalImages" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "taxable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "setupFee" DOUBLE PRECISION;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "internalNotes" TEXT;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "suggestedAddonIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
