import { scPageMetadata } from '@/lib/nycSeo'
import Link from 'next/link'
import type { Metadata } from 'next'
import { safeJsonLd } from '@/lib/jsonLd'
const BASE_URL='https://www.friendlypartyrentalsc.com'
export const metadata = scPageMetadata("/graduation-rentals","Graduation Party Rentals in Greenville, SC","Plan a graduation party in Greenville or Upstate South Carolina with tent, table, chair and party equipment rentals. Check your event date.")
export default function GraduationRentalsPage(){
 const jsonLd={'@context':'https://schema.org','@type':'CollectionPage',name:'Graduation Party Rentals',description:'Graduation party rental packages and equipment in Greenville, SC and Upstate South Carolina.',url:`${BASE_URL}/graduation-rentals`}
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(jsonLd)}}/><div className="max-w-5xl mx-auto px-4 py-12">
 <h1 className="text-3xl font-bold text-dark mb-2">Graduation Party Rentals in Greenville, SC</h1><p className="text-body mb-8">Celebrating a Greenville-area graduate? Friendly Party Rental SC supplies tents, tables, chairs, bounce houses, and concessions for graduation open houses and backyard celebrations throughout Greenville, Greer, Simpsonville, Mauldin, Taylors, Easley, Travelers Rest, Fountain Inn, and Piedmont, SC. Choose a graduation package below or build your own from our rental inventory. Review the included services, travel fee and tax before completing your order.</p>
 <h2 className="font-bold text-dark mb-4 text-xl">Graduation Party Packages</h2><div className="grid md:grid-cols-2 gap-6 mb-10"><div className="bg-white rounded-lg shadow-lg border-2 border-primary overflow-hidden p-6"><h3 className="text-xl font-bold text-dark mb-1">Graduation Party Package - Small (Seats 64)</h3><p className="text-3xl font-bold text-secondary mb-2">$665.00/day</p><p className="text-body text-sm mb-4">One 20&#39; x 30&#39; pole tent, 8 six-foot plastic folding tables, and 64 white plastic folding chairs. A great fit for a graduation open house or backyard celebration.</p><Link href="/category/party-rental-packages" className="inline-block bg-primary text-white px-4 py-2 rounded font-bold">Check Availability &amp; Book</Link></div><div className="bg-white rounded-lg shadow-lg border-2 border-primary overflow-hidden p-6"><h3 className="text-xl font-bold text-dark mb-1">Graduation Party Package - Large (Seats 100)</h3><p className="text-3xl font-bold text-secondary mb-2">$875.00/day</p><p className="text-body text-sm mb-4">One 30&#39; x 30&#39; pole tent, 10 tables, and 100 chairs. A graduation setup for celebrating with a big crowd of family and friends.</p><Link href="/category/party-rental-packages" className="inline-block bg-primary text-white px-4 py-2 rounded font-bold">Check Availability &amp; Book</Link></div></div>
 <p className="text-body text-sm mb-10">Need a different guest count? Call us at <a href="tel:864-610-5324" className="text-secondary underline">864-610-5324</a> and we&#39;ll help you size a tent and table/chair count for your graduation party. You can also browse <Link href="/category/party-rental-packages" className="text-secondary underline">all package deals</Link>.</p>
 <h2 className="font-bold text-dark mb-4 text-xl">Build Your Own Graduation Party Rental</h2><div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 mb-10 text-body">{[['/category/tent-rentals','Tent Rentals'],['/category/table-chair-rentals','Table & Chair Rentals'],['/category/bounce-house-rentals','Bounce Houses & Waterslides'],['/category/concession-machine-rentals','Concession Machines'],['/category/linen-rentals','Linens'],['/category/event-lighting-rentals','Event Lighting']].map(([url,label])=><Link key={url} href={url} className="block bg-white border rounded-lg p-4 hover:shadow-md">{label}</Link>)}</div>
 <h2 className="font-bold text-dark mb-4 text-xl">Why Greenville Families Choose Friendly Party Rental SC</h2><p className="text-body text-sm mb-2">Family-owned and operated, bringing Friendly Party Rental SC’s event-rental experience to Greenville and Upstate South Carolina. Clean, inspected equipment with delivery and collection from your event.</p>
 </div></>
}
