import { nycPageMetadata, NYC_SITE_URL } from '@/lib/nycSeo'
import Link from 'next/link'
import type { Metadata } from 'next'
import { safeJsonLd } from '@/lib/jsonLd'
import { NYC_SERVICE_AREA_SUMMARY } from '@/lib/nycServiceAreas'
const BASE_URL=NYC_SITE_URL
export const metadata = nycPageMetadata("/graduation-rentals","Graduation Party Rentals in Riverdale, Bronx, NY","Plan a graduation party in Riverdale or Downstate New York with tent, table, chair and party equipment rentals. Check your event date.")
export default function GraduationRentalsPage(){
 const jsonLd={'@context':'https://schema.org','@type':'CollectionPage',name:'Graduation Party Rentals',description:'Graduation party rental packages and equipment in Riverdale, Bronx, NY and Downstate New York.',url:`${BASE_URL}/graduation-rentals`}
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(jsonLd)}}/><div className="max-w-5xl mx-auto px-4 py-12">
 <h1 className="text-3xl font-bold text-dark mb-2">Graduation Party Rentals in Riverdale, Bronx, NY</h1><p className="text-body mb-8">Celebrating a Riverdale-area graduate? Friendly Party Rental NYC supplies tents, tables, chairs, bounce houses, and concessions for graduation open houses and backyard celebrations in {NYC_SERVICE_AREA_SUMMARY}. Choose a party package or build your own from our rental inventory. Review the included services, delivery fee and tax before completing your order.</p>
 <h2 className="font-bold text-dark mb-4 text-xl">Graduation Party Packages</h2><div className="bg-white rounded-lg shadow-lg border-2 border-primary overflow-hidden p-6 mb-10"><h3 className="text-xl font-bold text-dark mb-1">Tent, Table &amp; Chair Packages</h3><p className="text-body text-sm mb-4">Bundled tent, table and chair packages for graduation open houses and backyard celebrations are listed in our Party Rental Packages category. Package prices and availability are shown for your event date.</p><Link href="/category/party-rental-packages" className="inline-block bg-primary text-white px-4 py-2 rounded font-bold">View Party Packages</Link></div>
 <p className="text-body text-sm mb-10">Need a different guest count? Call us at <a href="tel:315-884-1498" className="text-secondary underline">315-884-1498</a> and we&#39;ll help you size a tent and table/chair count for your graduation party. You can also browse <Link href="/category/party-rental-packages" className="text-secondary underline">all package deals</Link>.</p>
 <h2 className="font-bold text-dark mb-4 text-xl">Build Your Own Graduation Party Rental</h2><div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 mb-10 text-body">{[['/category/tent-rentals','Tent Rentals'],['/category/table-chair-rentals','Table & Chair Rentals'],['/category/bounce-house-rentals','Bounce Houses & Waterslides'],['/category/concession-machine-rentals','Concession Machines'],['/category/linen-rentals','Linens'],['/category/event-lighting-rentals','Event Lighting']].map(([url,label])=><Link key={url} href={url} className="block bg-white border rounded-lg p-4 hover:shadow-md">{label}</Link>)}</div>
 <h2 className="font-bold text-dark mb-4 text-xl">Why Riverdale Families Choose Friendly Party Rental NYC</h2><p className="text-body text-sm mb-2">Family-owned and operated, bringing Friendly Party Rental NYC’s event-rental experience to Riverdale and Downstate New York. Clean, inspected equipment with delivery and collection from your event.</p>
 </div></>
}
