import Link from 'next/link'
import MarketingReviewQueue from '@/components/admin/MarketingReviewQueue'
import MarketingSchedulerStatus from '@/components/admin/MarketingSchedulerStatus'

export const dynamic = 'force-dynamic'

export default function SchedulerPage() {
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-bold text-gray-950">Schedule & review queue</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-gray-500">Check the scheduler and review saved custom campaigns. A scheduled review brings a draft here for your approval.</p></div><Link href="/admin/marketing/automations" className="rounded-lg bg-green-800 px-4 py-2.5 text-sm font-semibold text-white">Manage automatic campaigns →</Link></div><MarketingSchedulerStatus/><MarketingReviewQueue/><section className="rounded-xl border bg-white p-5"><h3 className="font-bold text-gray-950">Two ways to run your marketing</h3><div className="mt-4 grid gap-5 md:grid-cols-2"><div><h4 className="text-sm font-semibold">Automatic campaigns</h4><p className="mt-2 text-sm leading-6 text-gray-500">Selected campaigns use verified customer audiences, seasonal timing and sending limits. Review the actual emails and explicitly enable automatic sending in your setup.</p><Link href="/admin/marketing/automations" className="mt-3 inline-block text-sm font-semibold text-green-800 underline">See active rules and next eligible checks</Link></div><div><h4 className="text-sm font-semibold">Custom campaigns</h4><p className="mt-2 text-sm leading-6 text-gray-500">Create or edit a campaign in the builder, choose its audience, and schedule a review or launch it yourself. Scheduling a review does not send an email.</p><Link href="/admin/marketing/campaigns" className="mt-3 inline-block text-sm font-semibold text-green-800 underline">Open campaign library</Link></div></div></section><Link href="/admin/marketing/calendar" className="inline-block text-sm text-green-800 underline">Browse seasonal campaign ideas →</Link></div>
}
