name: Check Email Replies

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: {}

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call check replies endpoint
        run: |
          curl -f -X GET https://www.friendlypartyrentalsc.com/api/cron/check-replies -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
