name: One Year Reminders

on:
  schedule:
    - cron: '20 13 * * *'
  workflow_dispatch: {}

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call one year reminder endpoint
        run: curl -f -X GET https://friendlypartyrentalsc.com/api/cron/one-year-reminder
