name: Pre-Payment Reminders

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch: {}

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call pre-payment reminders endpoint
        run: |
          curl -f -X GET https://www.friendlypartyrentalsc.com/api/cron/pre-payment-reminders -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
