name: Pre-Rental Reminders

on:
  schedule:
    - cron: '10 13 * * *'
  workflow_dispatch: {}

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call pre-rental reminder endpoint
        run: curl -f -X GET https://www.friendlypartyrental.com/api/cron/pre-rental-reminder
