name: Thank You Emails

on:
  schedule:
    - cron: '15 13 * * *'
  workflow_dispatch: {}

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call thank you endpoint
        run: |
          curl -f -X GET https://www.friendlypartyrentalsc.com/api/cron/thank-you -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
